// Original editorial copy. Each guide owns one reader decision, not a keyword variant.
export default {
 'complete-guide': {
  title:'Viaje de kitesurf a Cartagena: itinerario y alojamiento',
  desc:'Organiza un viaje de kite de 3, 5 o 7 días: alojamiento, traslados, presupuesto, acompañantes y margen para el viento.',
  sections:[
   ['Empieza por los días disponibles, no por las horas de clase','Un viaje de kite funciona mejor cuando separas días de estancia, horas de enseñanza y oportunidades de viento. Llegar un viernes por la noche y salir el domingo al mediodía deja una sola jornada completa: no equivale a tres días de práctica. Anota tus horas reales de llegada y salida, el tiempo de traslado y los compromisos que no puedes mover. Después decide cuántas ventanas puedes dedicar a la playa.'],
   ['Tres días: una introducción con margen','Reserva el primer bloque útil para conocer la escuela, revisar tu nivel y empezar la progresión. Conserva otra ventana para continuar o recuperar una sesión aplazada. El último día conviene dejar tiempo para secar el equipo, ducharte y trasladarte. Si el viento no acompaña, no comprimas todas las horas en una sesión agotadora: la disponibilidad de calendario no convierte las condiciones en adecuadas.'],
   ['Cinco o siete días: continuidad y descanso','En cinco días puedes alternar sesiones y turismo sin depender de una única tarde. Con siete, resulta más fácil distribuir descansos y repetir habilidades antes de avanzar. Son ejemplos de organización, no promesas de autonomía. Una pareja con niveles distintos puede compartir alojamiento y transporte, pero necesitar objetivos o formatos de clase diferentes. Quien no practica necesita también un plan de sombra, comida y transporte.'],
   ['Dónde alojarte y cómo llegar a la playa','Compara una base cercana a La Boquilla con alojarte en una zona que priorice tus visitas por la ciudad. Calcula el coste y el tiempo de cada ida y vuelta, no solo la tarifa por noche. Antes de reservar habitación, pregunta si admite bolsas largas, dónde podrás secar material y si dispone de almacenamiento seguro. Para llegar desde el aeropuerto, comparte el punto exacto de encuentro: el nombre de una playa extensa no identifica una puerta ni una escuela.'],
   ['Presupuesto y preparación desde otro país','Separa curso o alquiler, alojamiento, comidas, transporte, equipaje deportivo y margen para cambios. Al comparar vuelos desde Estados Unidos o Europa, revisa cada trayecto y la compañía que lo opera; una conexión puede aplicar condiciones distintas a la bolsa. Comprueba los requisitos de entrada para tu nacionalidad en las fuentes oficiales correspondientes. La póliza de viaje debe mencionar la actividad y el tipo de práctica que realizarás; solicita al asegurador una confirmación escrita de coberturas y exclusiones.'],
   ['Un calendario que puedas adaptar','Deja visitas urbanas y planes flexibles para los momentos sin sesión. Evita comprometer una salida lejana justo después de una clase cuya hora depende del parte. Pide que la confirmación indique cómo se comunicará un cambio de horario. La mejor agenda es aquella que puedes reorganizar sin perder transportes, reservas de restaurante ni tu vuelo de regreso.']
  ]
 },
 'best-time': {
  title:'Mejor época para kitesurf en Cartagena: guía por meses',
  desc:'Compara la temporada seca y lluviosa para elegir fechas de kite en Cartagena, con margen de viaje y sin confundir clima con pronóstico.',
  sections:[
   ['Qué puede decirte una temporada','La climatología describe patrones observados durante muchos años; no indica qué sucederá la tarde de tu reserva. En Cartagena, la época seca y los alisios son referencias útiles para planear, pero la decisión de navegar exige un pronóstico reciente y una evaluación en la playa. Esta guía sirve para elegir fechas de viaje. Para decidir una sesión concreta, utiliza la guía de lectura del pronóstico.'],
   ['Diciembre: una transición que conviene tratar con flexibilidad','Diciembre suele considerarse parte del inicio de la ventana seca. No presupongas que todos sus días tendrán el mismo comportamiento ni que una llegada temprana del viento se repetirá en tus fechas. Si viajas durante fiestas, confirma alojamiento, traslado y espacio en el curso con anticipación. Una reserva de varias jornadas te ofrece más margen que concentrar toda la experiencia en la única tarde libre.'],
   ['Enero, febrero y marzo: planificar alrededor de la época seca','Estos meses pertenecen al periodo tradicionalmente más seco de la costa de Cartagena. Son una referencia razonable al priorizar un viaje enfocado en kite, sin que eso convierta un mes en una garantía de viento o de mar tranquilo. Un principiante necesita condiciones apropiadas para aprender, no simplemente el día más fuerte. No uses un calendario estacional para comprar una talla de cometa ni para decidir si puedes alquilar sin supervisión.'],
   ['Abril y el periodo de mayo a noviembre','Abril requiere prestar atención a la transición estacional. Durante el resto del año aumenta la importancia de revisar lluvias, avisos y ventanas concretas. No deduzcas que una estación más lluviosa significa ausencia permanente de viento: tampoco que una ráfaga asociada a una nube sea una oportunidad de práctica. Si tu viaje coincide con este periodo, organiza otras actividades y evita una agenda que dependa de navegar todos los días.'],
   ['Cómo escoger entre dos fechas','Compara primero cuántos días completos tendrás, después la flexibilidad del alojamiento y finalmente el objetivo del viaje. Una estancia más larga con horarios adaptables puede ofrecerte una mejor logística que una visita muy corta en un mes popular. Pide a la escuela que explique cómo recupera horas no realizadas y qué sucede cuando no existe otra ventana antes de tu salida. Conserva esa respuesta junto con la confirmación de reserva.'],
   ['Qué datos consultar antes de comprar el viaje','La climatología de Cartagena publicada por CIOH-DIMAR aporta el contexto estacional. Los boletines y avisos vigentes sirven para revisar condiciones cercanas a la fecha. Son escalas de información distintas. No publicamos porcentajes de días navegables, velocidades mensuales inventadas ni una puntuación de viento: esos números necesitarían una serie, una estación, un periodo y un método explícitos.']
  ]
 },
 'first-lesson': {
  title:'Primera clase de kitesurf: preparación y qué esperar',
  desc:'Qué practicarás en tu primera clase, cómo prepararte, qué ropa llevar y cómo hablar de natación, miedo, edad y necesidades personales.',
  sections:[
   ['La primera meta es controlar, no subirte a la tabla','Una introducción debería ayudarte a entender el espacio de práctica, la cometa y la comunicación con el instructor. El orden y los ejercicios dependen de tu experiencia y de las condiciones. Puede haber explicación en tierra, reconocimiento de equipo y trabajo de control antes de entrar al agua. Terminar la primera sesión sin navegar sobre la tabla no significa haber desaprovechado la clase.'],
   ['Qué contar antes de llegar','Indica que empiezas desde cero, cómo te sientes nadando en el mar y si has practicado deportes de tabla. Si te inquieta perder el control, alejarte de la orilla o caer al agua, dilo con esas palabras. El instructor puede explicar cómo se organiza el ejercicio y acordar señales de pausa. No ocultes una limitación para entrar en un grupo: una conversación previa ayuda a decidir si el formato encaja contigo.'],
   ['Natación, edad y condición física','Un chaleco no sustituye la capacidad de desenvolverte en el agua. La escuela debe valorar si puedes participar en la actividad propuesta. Para menores, pide los criterios de admisión, la participación del responsable y la disponibilidad de equipo adecuado; no hay una edad publicada aquí que garantice aceptación automática. Tampoco necesitas demostrar fuerza tirando de la barra: comprender las instrucciones, mantener atención y reconocer el cansancio son parte de la preparación.'],
   ['Ropa y objetos que sí ayudan','Lleva ropa de baño que quede firme y una prenda de protección solar cómoda bajo el arnés. Evita accesorios que puedan engancharse y guarda teléfono, joyas y documentos fuera de la zona de práctica. Añade agua, toalla y una muda para el regreso. Pregunta por el calzado en función del lugar de entrada; no elijas uno que se salga fácilmente ni presupongas que la playa tiene el mismo fondo en toda su extensión.'],
   ['Cómo saber si estás progresando','Al terminar, pide un resumen de lo que realizaste con ayuda y de lo que pudiste repetir por tu cuenta. Por ejemplo, reconocer una señal y responder correctamente es un avance más preciso que decir que la sesión estuvo bien. Anota la habilidad que se trabajará después. Si cambias de instructor o de escuela, ese registro transmite mejor tu nivel que el número de horas que pagaste.'],
   ['Una pregunta útil para el instructor','Pregunta: “¿Qué debo demostrar antes de pasar al siguiente ejercicio?”. La respuesta debería describir una habilidad observable. Así puedes disfrutar del aprendizaje sin comparar tu ritmo con un vídeo o con otro alumno. El objetivo de la introducción es construir una base que permita continuar, no terminar un temario a cualquier coste.']
  ]
 },
 'how-long': {
  title:'Cuánto se tarda en aprender kitesurf: etapas reales',
  desc:'Distingue horas de curso, primeros water starts y autonomía. Aprende a evaluar tu progreso y preparar la siguiente sesión.',
  sections:[
   ['Horas contratadas y nivel alcanzado son medidas diferentes','Un paquete de ocho horas describe tiempo de enseñanza, no una certificación automática de independencia. Dos personas con el mismo tiempo pueden necesitar tareas distintas al terminar. Influyen la continuidad, el tiempo efectivo de práctica, las condiciones y lo que cada persona ya domina. Compara programas por las habilidades que evalúan y por cómo registran el progreso, además de comparar su duración.'],
   ['Etapa de control: repetir sin depender de una corrección constante','La base incluye conocer el equipo, entender el área y controlar la cometa dentro del ejercicio indicado. Antes de añadir dificultad, el instructor debe poder observar respuestas consistentes. Hacer una maniobra una vez por casualidad no es lo mismo que reproducirla. Pide que se distingan las acciones que ejecutas después de una indicación de aquellas que reconoces y resuelves por tu cuenta.'],
   ['Body drag y primeros water starts','El body drag permite trabajar desplazamiento en el agua y recuperación de la tabla. El water start añade coordinación entre cometa, cuerpo y tabla. Una salida breve puede ser un buen avance, pero todavía quedan frenado, continuidad y control de la trayectoria. Si el intento falla, identifica con el instructor una variable para trabajar en la siguiente repetición; cambiar todo a la vez hace difícil entender qué funcionó.'],
   ['Ceñir: volver hacia el lugar del que saliste','Navegar unos metros y volver al punto previsto son objetivos distintos. La ceñida requiere gestionar dirección y recorrido de forma repetible, dentro de las condiciones adecuadas. El progreso útil no es solo mantenerte de pie: también debes controlar la velocidad, detenerte y conservar espacio respecto a otras personas. No pruebes a compensar una deriva persistente alejándote más de la costa.'],
   ['Qué significa autonomía','La independencia implica tomar decisiones, manejar situaciones previstas y conocer límites, además de navegar. La progresión de IKO distingue niveles de descubrimiento, intermedio e independiente; sirve como referencia para conversar sobre habilidades, no para prometer que un paquete concreto otorga un nivel. Una escuela de alquiler puede revisar tu capacidad actual aunque presentes un registro de cursos anteriores.'],
   ['Cómo aprovechar la próxima sesión','Lleva un registro breve: habilidad practicada, asistencia necesaria, dificultad principal y objetivo siguiente. Si has pasado tiempo sin navegar, dedica parte de la sesión a una revisión. Es preferible reservar un refuerzo para resolver una carencia concreta que repetir un curso por su nombre o contratar material suponiendo que las horas acumuladas equivalen a práctica reciente.']
  ]
 },
 'safety-checklist': {
  title:'Seguridad en kitesurf: revisión antes de entrar al agua',
  desc:'Organiza la revisión de entorno, equipo, comunicación y retorno; entiende qué practicar con un instructor antes de navegar de forma independiente.',
  sections:[
   ['Entorno: mira también hacia dónde podrías derivar','Antes de montar, localiza bañistas, obstáculos, otras líneas, accesos y salidas posibles. Una zona despejada en el punto de lanzamiento puede terminar en un área complicada a sotavento. Comenta con la escuela cómo afecta la dirección del viento a ese recorrido. Si no puedes explicar dónde terminarías al dejar de avanzar, todavía falta información para decidir la salida.'],
   ['Equipo: identifica el sistema que llevas hoy','Comprueba que el conjunto corresponde al uso previsto y que sus componentes están en condiciones adecuadas. Familiarízate con el sistema de liberación y las instrucciones del fabricante con ayuda competente. No des por hecho que todas las barras funcionan igual. Una línea con daño visible, una pieza que no encaja o un comportamiento extraño requiere detener la preparación y revisar el problema.'],
   ['Comunicación y espacio compartido','Acuerda las señales de lanzamiento, aterrizaje y pausa con la persona que te asiste. No ayudes a lanzar una cometa si no sabes cómo hacerlo ni interpretes un gesto ambiguo como autorización. En la playa, conserva corredores de paso y evita dejar líneas cruzando zonas de uso público. Las reglas de prioridad se aprenden antes de compartir el agua; tener prioridad no elimina la obligación de evitar una colisión.'],
   ['Retorno y autorrescate','Antes de entrar, identifica el lugar previsto de regreso, el apoyo disponible y qué harás si debes interrumpir la sesión. El autorrescate es una competencia práctica que se aprende y ensaya con un instructor; una secuencia escrita no sustituye ese entrenamiento. Si nunca lo has practicado con tu equipo, dilo en la evaluación de nivel. La distancia a la costa debe formar parte de la decisión, no descubrirse cuando surge un problema.'],
   ['Cansancio, calor y criterio para detenerte','Prepara sombra, agua y protección solar, y programa descansos antes de que la concentración se deteriore. No alargues una sesión solo para consumir todo el tiempo contratado. Si las condiciones cambian o no entiendes una instrucción, pide parar y reevaluar. Esta lista organiza una conversación previa: no certifica que el mar, el equipo ni una persona sean aptos para navegar.'],
   ['El cierre de la sesión también cuenta','Avisa al responsable de tu regreso, recoge el material sin bloquear la playa y registra cualquier golpe, pérdida de presión o funcionamiento irregular. Un problema pequeño detectado al salir puede condicionar el siguiente uso. La revisión posterior evita que otra persona reciba un equipo con una incidencia que todavía no conoce.']
  ]
 },
 'la-boquilla-guide': {
  title:'La Boquilla y otros spots de Cartagena: cómo elegir',
  desc:'Compara la logística de La Boquilla, Manzanillo, Las Velas y Salinas del Rey sin asumir que todas las playas sirven para el mismo nivel.',
  sections:[
   ['La Boquilla: coordina un punto exacto','La Boquilla es la referencia de encuentro de este sitio. Para llegar, utiliza el enlace de la escuela y confirma la ubicación del día con el equipo. Una playa extensa puede tener accesos y actividades diferentes: no basta con pedir que te dejen “donde hacen kite”. Antes de montar, identifica el sector de enseñanza, la circulación de otras personas y el lugar acordado para finalizar.'],
   ['Si eres principiante, el nombre del spot no decide por ti','La elección depende del ejercicio, el espacio disponible, la dirección del viento, el estado del agua y la asistencia. Una fotografía con agua tranquila no demuestra cómo estará la playa durante tu clase. Pregunta cómo se organiza la separación entre alumnos, practicantes independientes y bañistas. Si la zona prevista no permite el ejercicio, cambiar el horario o el sector puede ser más útil que insistir en el lugar original.'],
   ['Manzanillo del Mar: suma la logística al análisis','Manzanillo está al norte de Cartagena y requiere coordinar acceso y desplazamiento. Antes de salir, confirma qué servicio se prestará allí, dónde será el encuentro y cómo regresarás. No asumas que el soporte, las instalaciones o el material de una escuela se trasladan automáticamente contigo. Calcula el viaje de ida y vuelta antes de comparar una sesión en este sector con otra en La Boquilla.'],
   ['Las Velas: confirma el sector y el uso de la playa','Para una sesión en Las Velas, pide una localización precisa y la evaluación local del día. La cercanía a otras actividades de playa hace especialmente importante conocer el área disponible y los corredores de entrada y salida. No recomendamos desplazarte con el equipo únicamente porque el mapa marque un spot: el mapa ayuda a ubicarte, pero no confirma condiciones ni disponibilidad de asistencia.'],
   ['Salinas del Rey: una salida fuera de Cartagena','Salinas del Rey está en el departamento del Atlántico; trátala como una excursión con transporte y regreso propios. Compara tiempo total fuera del alojamiento, equipo que llevarás y coordinación con el operador local. El interés de conocer otro spot debe compensar esa logística. No prometemos tiempos fijos de carretera ni condiciones mejores por el mero hecho de cambiar de playa.'],
   ['Una comparación que sí puedes hacer antes de reservar','Para cada opción anota punto de encuentro, transporte, nivel requerido, servicio contratado, asistencia y alternativa si cambia el tiempo. Cuando falte uno de esos datos, solicítalo antes de comprometer el desplazamiento. Utiliza el mapa de spots como apoyo geográfico y el contacto local para la decisión operativa.']
  ]
 },
 'packing-list': {
  title:'Equipaje de kitesurf: qué llevar y cómo preparar el vuelo',
  desc:'Prepara ropa, material y bolsa deportiva; revisa peso, medidas, conexiones y documentación de tu equipo antes de volar.',
  sections:[
   ['Divide el equipaje en tres grupos','Separa los objetos personales de playa, el material técnico que realmente usarás y los documentos o confirmaciones del viaje. Si contratas un curso con equipo, pregunta primero qué incluye: llevar una cometa por si acaso puede añadir coste sin utilidad. Para un viaje con material propio, haz un inventario con marca, modelo, talla y fotografías del estado antes de cerrar la bolsa.'],
   ['Para la clase y para después','Prepara ropa de baño firme, protección solar adecuada, toalla, agua y ropa seca para regresar. Guarda los objetos de valor fuera de la zona de montaje. Una bolsa para prendas húmedas evita mezclar todo al terminar, pero no debería convertirse en almacenamiento prolongado del material mojado. Si tienes varias sesiones, piensa dónde podrás secar cada pieza entre usos.'],
   ['Comprueba medidas, peso y compañía operadora','Las condiciones de equipaje deportivo dependen de la aerolínea, la tarifa y el trayecto. Consulta la página oficial de quien opera cada vuelo y guarda su respuesta cuando debas declarar una bolsa. Mide el conjunto ya preparado, incluidas ruedas y protecciones, y pésalo con todos los accesorios. No asumas que llamarlo “bolsa de golf” cambia legítimamente las condiciones aplicables a una tabla de kite.'],
   ['Protección y objetos restringidos','Sigue las instrucciones del fabricante para embalar y desmontar componentes. Protege zonas rígidas para que no presionen el tejido y evita que piezas sueltas se muevan dentro de la bolsa. Herramientas, adhesivos y baterías pueden tener restricciones de transporte: compruébalas con la aerolínea y la autoridad aeroportuaria correspondiente. No transfieras productos a envases sin identificar para intentar evitar un control.'],
   ['Entrega y recogida de la bolsa','Guarda el comprobante de equipaje y fotografía el exterior al entregarlo. Al recogerlo, revisa cierres, golpes y el contenido antes de abandonar el área si observas una incidencia. Sigue el procedimiento de la compañía para reportarla. Coordina también el vehículo desde el aeropuerto: una bolsa larga puede necesitar espacio que no has previsto al reservar el traslado.'],
   ['Kit de repuestos con un límite claro','Lleva solo repuestos compatibles que sepas identificar y utilizar según el fabricante. Un pequeño kit puede resolver necesidades de viaje, pero no sustituye el diagnóstico de una línea dañada o una rotura estructural. Incluye datos del modelo y acceso al manual; suelen ser más útiles que una colección de pegamentos elegidos sin conocer el material.']
  ]
 },
 'kite-size': {
  title:'Tamaño de kite: qué revisar antes de elegir una cometa',
  desc:'Entiende cómo intervienen peso, viento, tabla, modelo y nivel al elegir tamaño de kite, y por qué una tabla universal no basta.',
  sections:[
   ['La cifra en metros cuadrados no describe todo el equipo','Dos cometas con la misma superficie pueden tener rangos y comportamiento diferentes. La talla debe interpretarse dentro de la gama, el año y las instrucciones del modelo, junto con la barra compatible. Por eso no publicamos una tabla universal que transforme una velocidad de viento en una talla supuestamente válida para cualquier persona.'],
   ['Los datos que debes reunir','Anota tu peso aproximado, nivel actual, tipo y tamaño de tabla, modelo de cometa y rango que declara el fabricante. Añade el viento observado, la diferencia entre media y rachas y la dirección respecto a la costa. Si falta el modelo o desconoces el estado del material, esa incertidumbre debe resolverse antes de escoger, no compensarse copiando la talla de otro navegante.'],
   ['Por qué mirar solo la media puede engañar','Una lectura media no describe por sí sola la variación durante la sesión. Dos partes con la misma media pueden tener rachas muy distintas, y una medición lejos del punto de práctica puede no representar la playa. La selección debe revisarse con observación local. Un principiante no debería interpretar el límite superior de una tabla comercial como un objetivo de entrenamiento.'],
   ['Tabla y objetivo de la sesión','El tipo de tabla y la actividad cambian el conjunto que se está evaluando. No traslades sin revisión una elección hecha para una twin-tip a una sesión de foil. Tampoco conviertas una recomendación recibida ayer en una regla para el resto de las vacaciones. Explica si vas a recibir clase, practicar una habilidad o navegar de forma independiente para que la evaluación corresponda al uso real.'],
   ['Un ejemplo de consulta bien planteada','En lugar de preguntar “¿llevo la de doce?”, comunica: “Peso aproximadamente X, uso esta tabla, mi cometa es este modelo y año, y mi nivel actual es este”. Envía el pronóstico como contexto y pide confirmar en la playa. La respuesta útil puede incluir cambiar de equipo o no salir; no tiene por qué ser siempre una cifra.'],
   ['Si vas a alquilar','Consulta si existe equipo compatible disponible y cómo se hará la revisión de nivel. No pagues una talla concreta como si eso garantizara su uso durante todo el día. Una reserva debería permitir entender qué ocurre si el material adecuado para las condiciones no está disponible.']
  ]
 },
 'book-whatsapp': {
  title:'Reservar kitesurf: datos, pago y cambios por clima',
  desc:'Envía una solicitud útil, confirma el total y distingue consulta, reserva y sesión confirmada antes de pagar por una experiencia de kite.',
  sections:[
   ['Envía los datos que permiten preparar una propuesta','Incluye fechas disponibles, hora de salida de Cartagena, número de personas, experiencia reciente y objetivo. Añade el idioma de enseñanza y si necesitas equipo o traslado. Describe habilidades concretas: “hago water start pero no regreso al punto de salida” orienta mejor que “nivel medio”. No envíes documentos de identidad, datos bancarios ni información sensible como parte de una consulta inicial.'],
   ['Mensaje de ejemplo','“Hola, estaremos en Cartagena del día X al día Y. Somos dos personas: una empieza desde cero y otra ha tomado clases, pero aún no navega de forma independiente. Podemos ir a la playa en estas franjas y salimos de la ciudad a esta hora. Queremos enseñanza en español y necesitamos equipo. ¿Qué formato recomiendan, cuál es el total y qué ocurre si no se completa la sesión por clima?” Ajusta el ejemplo a tu situación real.'],
   ['Consulta no significa reserva confirmada','Una respuesta automática o una recomendación de curso no confirma un cupo. Pide que la propuesta identifique servicio, participantes, duración, precio, moneda y condiciones de pago. Distingue la fecha reservada de la hora operativa, que puede confirmarse más cerca de la sesión. Guarda la confirmación y el canal por el que recibirás cualquier cambio.'],
   ['Antes de pagar','Comprueba quién recibe el pago y que coincida con la información del operador. Solicita el total, qué se paga ahora y qué queda pendiente; pregunta también por equipo, transporte y otros conceptos. Este artículo no establece un porcentaje de anticipo ni una política de devolución: deben constar en la propuesta que recibas. No deduzcas una política porque otra escuela la aplique.'],
   ['Cancelación y reprogramación son casos distintos','Pregunta por separado qué ocurre si tú cancelas, si el operador suspende por condiciones y si solo se completa parte del tiempo. Aclara cómo se contabilizan las horas realizadas y qué alternativa existe cuando tu vuelo impide reprogramar. Conserva estas respuestas por escrito antes del pago. Así puedes comparar ofertas sobre la misma base, sin asumir que todos los cambios tienen la misma solución.'],
   ['Con cuánta anticipación contactar','Contacta cuando conozcas tus fechas, especialmente si necesitas un idioma, un grupo o varios días de enseñanza. La anticipación permite organizar recursos; no garantiza el viento. El día anterior o en el momento acordado, confirma ubicación, hora, responsable y qué llevar. Evita salir hacia una playa basándote únicamente en un intercambio antiguo.']
  ]
 },
 'choose-course': {
  title:'Qué curso de kitesurf elegir según tus habilidades',
  desc:'Compara introducción, progresión, refuerzo y clases compartidas según lo que sabes hacer, tu tiempo real de práctica y tu objetivo.',
  sections:[
   ['Empieza por una habilidad comprobable','Si nunca has controlado una cometa, busca una introducción. Si has practicado en el agua, explica si recuperas la tabla, haces water start, navegas en ambos sentidos y vuelves al punto de salida. Estas referencias permiten proponer un punto de partida. “Hice un curso hace años” aporta contexto, pero no determina qué ejercicios puedes realizar hoy.'],
   ['Introducción, progresión o refuerzo','Una introducción sirve para conocer el deporte y construir bases. Un programa de progresión ofrece continuidad entre sesiones. Un refuerzo tiene sentido cuando existe una dificultad identificada, como estabilizar el water start o trabajar el regreso. El nombre comercial no basta: pide al instructor que describa el objetivo inicial y qué criterio utilizará para ajustar el contenido.'],
   ['Clase privada: atención y ritmo individual','Pregunta si el instructor y el equipo estarán dedicados a ti durante el bloque contratado, cómo se distribuyen explicación y práctica y cuándo se hacen pausas. La atención individual puede facilitar correcciones específicas, pero no elimina la necesidad de condiciones adecuadas ni convierte cada minuto en tiempo dentro del agua. Compara el alcance real, no solo la etiqueta “privada”.'],
   ['Clase compartida: entiende los turnos','Dos personas pueden alternar observación y práctica, pero conviene conocer cuántas cometas e instructores participan. Pregunta si la duración anunciada corresponde al bloque total o al tiempo de práctica de cada alumno. Si uno empieza desde cero y otro ya navega, consulta cómo se evitará que ambos sigan un objetivo que solo sirve a uno.'],
   ['Curso y alquiler resuelven necesidades diferentes','El alquiler proporciona material bajo unas condiciones; no equivale a una clase ni garantiza supervisión técnica continua. Si todavía dependes de indicaciones para volver, detenerte o gestionar incidencias, solicita una evaluación y un formato de enseñanza. No es una comparación útil elegir alquiler solo porque el precio por hora parezca menor.'],
   ['Cómo comparar dos propuestas','Anota objetivo, duración, proporción de alumnos por instructor, equipo, idioma, lugar y política de horas no realizadas. En el catálogo de cursos encontrarás las opciones comerciales; utiliza esta guía para formular preguntas, no como promesa de que todas las opciones incluyen lo mismo. La propuesta adecuada debería relacionar el servicio con una necesidad concreta de tu nivel.']
  ]
 },
 'rental-requirements': {
  title:'Alquilar equipo de kitesurf: autonomía y condiciones',
  desc:'Qué revisar para alquilar material, cómo acreditar tu nivel y cuándo conviene llevar tu propio equipo a Cartagena.',
  sections:[
   ['La evaluación se refiere a tu capacidad actual','Antes de alquilar, explica cuándo navegaste por última vez, en qué condiciones y con qué equipo. Un registro de formación ayuda, pero el operador puede necesitar comprobar tu autonomía en el lugar. Debes distinguir haber completado un curso de poder gestionar una sesión sin enseñanza continua. Si tienes dudas sobre una habilidad, indícala antes de que se asigne el material.'],
   ['Qué debe quedar claro sobre la asistencia','Pregunta quién ayuda en lanzamiento y aterrizaje, qué vigilancia existe y qué servicio se activa ante una incidencia. “Alquiler” no describe por sí solo rescate, traslado ni clase. Solicita límites de área, horario de retorno y canal de comunicación. Si el plan que necesitas requiere acompañamiento permanente, compara un servicio supervisado o una sesión de refuerzo.'],
   ['Revisión al recibir el material','Comprueba con el responsable qué piezas recibes y cómo funcionan. Registra daños preexistentes con fotografías y señala cualquier duda sobre desgaste o compatibilidad antes de usarlo. Revisa que las condiciones de viento y el conjunto asignado correspondan a la evaluación. No aceptes una pieza desconocida simplemente porque sea la única disponible.'],
   ['Depósito, daños y tiempo contratado','Aclara importe o garantía, forma de devolución, responsabilidades y procedimiento si aparece una incidencia. Pregunta cuándo empieza y termina el cómputo del alquiler y qué sucede si el viento cambia durante el bloque. La disponibilidad de un modelo concreto y el precio final deben confirmarse en la propuesta; este artículo no sustituye el contrato de alquiler.'],
   ['Alquilar o llevar equipo propio','Compara el coste total de equipaje y traslados con la duración del viaje y la disponibilidad local. Tu material ofrece familiaridad, pero exige transporte, almacenamiento y cuidado. Alquilar reduce la carga de viaje, aunque necesitas verificar tallas, compatibilidad y condiciones de entrega. Si llevas solo parte del conjunto, confirma por adelantado que las piezas pueden utilizarse juntas.'],
   ['Devolución sin dudas','Entrega cada componente con el responsable, comunica cualquier golpe o anomalía y solicita cierre del servicio y de la garantía cuando corresponda. No dejes el material en un punto sin acordar su recepción. Una devolución documentada evita que una incidencia posterior se confunda con el estado en que lo entregaste.']
  ]
 },
 'wind-sources': {
  title:'Cómo leer el pronóstico de viento para una sesión de kite',
  desc:'Revisa hora, unidades, rachas, dirección y avisos; decide qué preguntar a la escuela y qué hacer cuando el viento no permite la sesión.',
  sections:[
   ['Primero verifica qué lugar y qué hora estás leyendo','Una captura de una aplicación puede corresponder a otro punto, otra fecha o una zona horaria diferente. Comprueba ubicación, hora de emisión, periodo previsto y unidades. Nudos, kilómetros por hora y metros por segundo no son intercambiables. Conserva el enlace o la información de origen para que el instructor pueda interpretar el mismo dato que tú.'],
   ['Media y rachas responden preguntas distintas','La media resume el viento durante un intervalo; la racha representa un pico. La separación entre ambas ayuda a reconocer variabilidad, aunque ninguna cifra sustituye la observación local. No existe en esta guía un umbral único de viento apto para todos los principiantes. El nivel, el equipo, el agua y la dirección deben evaluarse juntos.'],
   ['Dirección, costa y posibilidad de retorno','Asegúrate de comprender si la herramienta indica de dónde viene el viento o hacia dónde dibuja su flecha. Después relaciona esa dirección con el tramo de costa concreto. Dos playas cercanas pueden tener una orientación distinta. Pide al instructor que explique cómo esa combinación afecta el área de práctica y el regreso antes de decidir una talla o una salida.'],
   ['Mañana o tarde: compara ventanas, no eslóganes','No reserves una hora suponiendo que todas las tardes mejoran o que todas las mañanas son tranquilas. Revisa la evolución prevista durante el bloque completo y contrástala cerca de la sesión. Los cambios de dirección, nubosidad y avisos importan tanto como una cifra de velocidad. Los alisios explican un patrón regional, pero no detallan por sí solos lo que sucede en tu playa.'],
   ['Qué hacer si no hay condiciones','Pide la evaluación del operador y las alternativas contempladas en tu reserva. Puede haber reprogramación o trabajo en tierra cuando tenga sentido educativo y esté acordado; no debe presentarse cualquier actividad distinta como sustituto automático de las horas contratadas. Si no puedes volver otro día, consulta la solución prevista para esa situación específica.'],
   ['Consulta fuentes con funciones diferentes','El sistema meteorológico de DIMAR y sus boletines permiten revisar información y avisos oficiales. Una aplicación de modelos añade otra vista, y la observación de la escuela aporta contexto del punto de práctica. Si discrepan, no elijas simplemente el número que prefieres: solicita que se explique la diferencia. Una predicción es información para decidir, no autorización para entrar al agua.']
  ]
 },
 'kite-vs-wing': {
  title:'Kitesurf o wing foil: equipo, aprendizaje y diferencias',
  desc:'Compara cometa con líneas y wing de mano: espacio, tabla, habilidades iniciales y preguntas para escoger una primera experiencia.',
  sections:[
   ['De dónde viene la tracción','En kitesurf utilizas una cometa conectada por líneas a una barra. En wing empleas un ala que sostienes con las manos. Esa diferencia cambia la forma de preparar el equipo, coordinar movimientos y gestionar el espacio. No significa que una disciplina carezca de riesgos ni que aprender una convierta automáticamente en independiente en la otra.'],
   ['Tabla y primeras sensaciones','El kitesurf de iniciación suele trabajar con una tabla twin-tip. En wing foil se combina el ala con una tabla y un foil, aunque un programa puede empezar con ejercicios adaptados antes de volar sobre el agua. Pregunta qué material se utilizará en la introducción. Una imagen de alguien navegando elevado sobre el foil no describe necesariamente lo que harás en la primera clase.'],
   ['Qué aprenderás a coordinar','En kite, el control de la cometa y el trabajo con la tabla requieren una progresión conjunta. En wing, el equilibrio y la posición del ala plantean otro tipo de coordinación. La experiencia en surf, vela o deportes de tabla puede aportar familiaridad con ciertos movimientos, pero no reemplaza el aprendizaje del equipo y de los procedimientos específicos.'],
   ['Espacio y condiciones','La cometa requiere gestionar líneas y un área de montaje y operación. El wing no utiliza esas líneas largas, pero el conjunto de tabla y foil exige considerar profundidad y espacio en el agua. La idoneidad del lugar depende del material y del ejercicio. Evita elegir solo por la idea de que uno es “más fácil” en cualquier playa.'],
   ['Cómo elegir una introducción','Explica qué te atrae: aprender a navegar con cometa, probar el equilibrio sobre una tabla con ala o aprovechar experiencia previa. Pregunta por duración, equipo inicial, instructor y objetivos de la sesión. Compara oportunidades reales de enseñanza durante tus fechas. La mejor primera elección es aquella cuyo formato entiendes y que tiene condiciones apropiadas para tu aprendizaje.'],
   ['Si ya practicas una de las dos','Pide una evaluación para la nueva disciplina. Conserva los hábitos de observación y respeto al espacio compartido, pero no traslades automáticamente sistemas de seguridad ni técnicas de manejo. Aprender una actividad relacionada sigue necesitando una introducción al material concreto que vas a utilizar.']
  ]
 },
 'kite-repair': {
  title:'Cometa dañada: diagnóstico, reparación o sustitución',
  desc:'Distingue pérdidas de aire, desgarros y daños en líneas; prepara un diagnóstico y conoce qué comprobar antes de volver a usar la cometa.',
  sections:[
   ['Describe el síntoma antes de pedir una solución','Indica marca, modelo, año, talla, cuándo apareció el problema y si hubo un golpe o una reparación anterior. Añade una fotografía general y acercamientos con una referencia de escala. “Pierde presión después de cierto tiempo” aporta más información que “hay que cambiar el bladder”. El diagnóstico debe identificar el componente afectado antes de elegir una intervención.'],
   ['Bladder y válvulas: el punto visible no siempre es el origen','Una pérdida de presión puede estar relacionada con diferentes componentes del sistema inflable. No atribuyas el fallo automáticamente a la válvula que tienes a la vista. Evita desmontajes o adhesivos improvisados que oculten evidencias o dañen superficies. El técnico debe conocer el modelo y confirmar compatibilidad del repuesto, preparación y pruebas necesarias antes de devolver el equipo.'],
   ['Canopy, costuras y zonas que soportan carga','Un desgarro en el tejido, una costura abierta y un daño junto a un refuerzo no se evalúan igual. La ubicación, extensión e historial importan para decidir si una reparación puede recuperar el uso previsto. Una cinta que cubra visualmente una rotura no demuestra integridad. Entrega la cometa sin seguir usándola para evitar ampliar el daño mientras esperas el diagnóstico.'],
   ['Líneas y barra: no improvises compatibilidad','Las líneas, sus conexiones y el sistema de control forman un conjunto. Un nudo improvisado o una pieza parecida puede alterar su comportamiento. Si detectas desgaste, diferencia de longitudes o una liberación irregular, retira el conjunto de uso y solicita evaluación según el fabricante. El presupuesto debe identificar qué componente se repara o sustituye y con qué referencia.'],
   ['Qué debe incluir una propuesta de reparación','Pide diagnóstico, alcance, piezas, precio y plazo estimado, además de las limitaciones que permanecerán después del trabajo. Puede ser necesario inspeccionar físicamente el material antes de cerrar una cifra. Compara reparar y sustituir teniendo en cuenta el estado del conjunto, no solo el coste de tapar el daño visible. La disponibilidad de repuestos puede condicionar el plazo.'],
   ['Antes de volver al agua','Solicita la explicación del trabajo realizado y de las verificaciones que corresponden al modelo y al daño. Conserva fecha, piezas y fotografías para el historial del equipo. Una inspección y una reparación no eliminan la necesidad de revisar el material en cada uso. La página del servicio de reparación permite consultar disponibilidad; esta guía explica cómo preparar y entender el diagnóstico.']
  ]
 },
 'saltwater-gear-care': {
  title:'Cuidado del equipo de kite: secado, almacenaje y desgaste',
  desc:'Organiza el cuidado después de navegar: arena, secado, barra, líneas y almacenamiento según el manual de cada componente.',
  sections:[
   ['Empieza por el manual de cada pieza','La cometa, la barra, las líneas, la tabla y el arnés no tienen necesariamente las mismas instrucciones de limpieza. Identifica el modelo y consulta las indicaciones del fabricante antes de aplicar productos o rutinas. No conviertas el consejo recibido para una barra en una norma para todo el equipo. Las guías de mantenimiento sirven para prevenir deterioro; no reparan por sí mismas un componente ya dañado.'],
   ['Arena y secado antes de guardar','Evita arrastrar el material por superficies abrasivas y retira la arena sin frotarla contra el tejido. Organiza un secado adecuado antes del almacenamiento, siguiendo el manual y sin dejar el conjunto expuesto innecesariamente al sol. Si tienes que transportarlo húmedo, vuelve a abrirlo al llegar. Una bolsa cerrada en un vehículo caliente no es un lugar de secado.'],
   ['Barra y líneas: observa antes de enrollar','Comprueba si hay abrasión, cortes, nudos o cambios que no habías visto antes. Revisa especialmente las zonas de roce y conexiones. Si sospechas diferencias de longitud o un comportamiento irregular, consulta el procedimiento del modelo; no intentes compensarlo con nudos inventados. El cuidado rutinario debe incluir detectar cuándo una pieza necesita inspección profesional.'],
   ['Almacenamiento entre viajes','Escoge un lugar seco y protegido de calor excesivo, radiación directa y elementos que puedan dañar el material. Evita apoyar pesos o bordes duros sobre la bolsa. Guarda accesorios de forma que puedas identificarlos y mantener sus referencias. Antes de la próxima salida, revisa el equipo aunque haya estado almacenado sin uso: el tiempo guardado no certifica su estado.'],
   ['Lleva un historial sencillo','Registra compra, modelo, incidencias, mantenimiento y reparaciones. Una foto de una zona de desgaste permite comparar su evolución, aunque no sustituye una evaluación. Si prestas o alquilas tu equipo, informa de lo que debe conocer quien lo recibe. El historial también ayuda a un técnico a entender si un problema reaparece en la misma zona.'],
   ['Cuándo pasar del cuidado a la revisión técnica','Detén el uso ante cortes, costuras abiertas, pérdida de presión o dudas sobre un sistema de seguridad. Limpiar y secar no resuelve esos fallos. Lleva el material y su historial a revisión antes de planear otra sesión. Separar mantenimiento preventivo y reparación evita que una rutina bien intencionada oculte un problema que necesita una intervención distinta.']
  ]
 }
};
