export default [
['first-kite-purchase','Your first kitesurf equipment: decisions before buying','Consider ability, usual riding location, compatibility and maintenance before choosing a first setup.',[
['Buy for your usual riding','Equipment used on holiday does not necessarily define what you need at home. Describe where you will ride, how often and the training you have completed. Take that information to a professional assessment before selecting a size or model because of an attractive offer.'],
['Think of the complete setup','Kite, bar, lines, board and harness should be evaluated as a system. A kite’s price alone is not the cost of a usable setup. Request exact compatibility checks and information about spares, including the specifications for the model and year.'],
['Test with a purpose','A supervised trial lets you describe fit and sensations after familiarisation. You do not need the most advanced model: you need to understand why it suits your ability and surroundings. Compare ease of inspection and manufacturer support too.'],
['Budget for ownership','Add the bag, transport, storage and maintenance. Keep receipts, identification and manuals. If you are still establishing preferences and independence, continuing lessons with equipment selected for each exercise can improve your judgement before committing to a purchase.']]],
['used-kite-inspection','Buying a used kite: records and inspection','What to ask the seller and review with a specialist before choosing second-hand equipment.',[
['Identify the actual item','Request brand, model, year, size and current photographs of the complete equipment. Check that identification matches the listing. Ask about repairs and storage: “lightly used” tells you less than a specific, verifiable history.'],
['Photographs have limits','Images of seams, fabric, valves and connections help identify questions but do not certify integrity. An in-person inspection by a competent specialist may reveal problems absent from photographs. A clean appearance does not guarantee remaining service life.'],
['Include the bar and spare parts','For a complete set, identify the bar and lines too. Confirm compatibility using manufacturer documentation and check parts availability. A low price becomes less attractive if essential components need replacement or a specific spare cannot be obtained.'],
['Decide using the total cost','Add inspection, anticipated repairs and missing components before comparing alternatives. Request evidence of condition and clear sale terms. If provenance, compatibility or damage cannot be clarified, that uncertainty should influence the decision rather than disappear behind the discount.']]],
['twin-tip-directional-foil','Twin-tip, directional board and foil: choosing your lesson','Understand three board types and why moving between them requires different learning objectives.',[
['Twin-tip','A bidirectional board is designed for riding in both directions. It is a common reference in kite introductions, although the school selects the specific equipment. Using one does not mean balance, water starts and direction control develop automatically.'],
['Directional board','A directional board has a defined orientation and relates to different disciplines and manoeuvres. Twin-tip experience provides context, but adaptation deserves specific teaching. Explain your current board and intended skill rather than simply requesting an advanced level.'],
['Foil','This setup adds a mast and submerged surfaces that change the board’s relationship with the water. Depth, equipment and control require a particular assessment. Do not select a foil lesson solely because it looks like a variation of a familiar board.'],
['Choose by the transition you want','Explain your starting discipline and intended destination, such as twin-tip kiting to kitefoil. The proposal can then address existing and new skills. Comparing only litres, centimetres or board prices leaves out the purpose of the lesson.']]],
['inflatable-vs-foil-kite','Inflatable versus foil kites: understanding the structures','Clarify the difference between a foil kite and a hydrofoil board before discussing equipment.',[
['Two uses of the word foil','Foil can describe a type of kite or the submerged assembly beneath a board. They are different components and are not necessarily used together. When seeking advice, send the full name or a photograph to avoid a recommendation based on misunderstanding.'],
['Kite structure','An inflatable kite uses inflated elements to maintain its structure. A foil kite uses cells and a different construction. This affects preparation, handling and maintenance; it does not by itself establish that either option suits every student.'],
['Intended use comes first','Discipline, surroundings and experience should precede selection. Do not choose a model because someone rides it in light wind in a video: weight, board, technique and conditions may differ. Ask for an explanation of the complete setup you will use.'],
['Specific documentation','Review the particular unit’s manual, systems and compatibility before changing types. Experience with one construction does not replace familiarisation with another. For a first lesson, ask which equipment the school selects for the exercise and why.']]],
['harness-fit','How to explain that a kite harness does not fit well','Distinguish size, positioning and discomfort so you can request a fitting check before continuing.',[
['The printed size is not enough','Two harnesses labelled the same size may fit differently. Model and body shape affect the feeling. During preparation, request a fitting check and explain if an area presses uncomfortably or the setup moves in a way you do not understand.'],
['Describe where and when','“It feels uncomfortable” is a start; pointing out where and when helps more. Distinguish discomfort when putting it on from a problem arising during the exercise. Do not wait until the end to mention something affecting your concentration.'],
['Make changes with assistance','Avoid changing connections yourself while still learning. Ask the instructor to review the setup before continuing. Familiarisation includes recognising components and systems, rather than simply tightening a strap until it feels secure.'],
['Before buying a harness','Try the model with appropriate guidance and check compatibility with your intended equipment. Keep the exact reference of a suitable model. Buying by size alone or by a photograph does not ensure the same fit.']]],
['bar-compatibility','Can any kite bar be used with any kite?','Gather model, year, line and system information to verify compatibility before combining equipment.',[
['Counting lines is not enough','The same number of lines does not establish compatibility. Configuration and the manufacturer’s system matter. Identify both kite and bar by brand, model and year before combining them; “four-line bar” leaves essential information unresolved.'],
['Find documented confirmation','Consult the manual or manufacturer support for that exact combination. Do not extend advice for another year or size without verification. If you cannot find the information, take both references to a professional who can assess the setup before use.'],
['Compatibility and condition are separate questions','An approved combination can still have uneven lines, wear or damaged parts. Condition checks remain necessary. Conversely, a bar that looks new is not necessarily suitable for the kite you want to connect.'],
['When renting or repairing','Mention replaced components and keep their references. Do not mix parts from two rental sets to solve a shortage without approval. For remote enquiries, send readable identification and overall photographs rather than attempting an improvised flight test as validation.']]],
['helmet-vest-choice','Kitesurf helmets and vests: questions about protection','Understand why fit, purpose and product specifications matter more than appearance.',[
['Each item has a purpose','An impact vest and a flotation device should not be treated as equivalent simply because both cover the torso. Read the product identification and ask about its purpose. Selection should fit the exercise and the school’s plan.'],
['Fit needs checking','An available size is not automatically a suitable size. Before starting, mention if the helmet moves or a garment restricts required movement. Check it with the actual equipment you will use, including the harness where appropriate.'],
['Do not infer specifications from a photograph','Shape, colour and thickness do not prove certification. When purchasing, ask for documentation and the exact manufacturer reference. When booking, check what the school supplies and what the student must bring rather than assuming every package is identical.'],
['Protection does not replace learning','These items do not remove the need for instruction, environmental assessment and practice limits. Report damage or fitting problems before continuing. The decision should not depend on tolerating discomfort to avoid delaying the group.']]],
['radio-lesson','Kitesurf lessons with a radio: uses and limits','Agree on communication, signals and operation when a school offers radio-assisted teaching.',[
['What a radio can do','A radio allows instructions without depending entirely on shouting across a distance. It can support teaching, but its presence alone does not prove greater attention or fewer students. Ask how it fits into session organisation.'],
['Clarify the communication type','Check whether you can reply or only listen, and how to communicate a difficulty. An instruction you have not understood needs a way to be clarified. Test communication before moving away, with the equipment fitted as it will be used.'],
['If you cannot hear','Agree beforehand what to do if communication is lost and which visual signals apply. Do not invent a response during the exercise. Specific instructions must come from the person leading the session who knows the area, equipment and your ability.'],
['What to confirm when booking','Ask whether the radio is included in your option and available that day. A promotional image does not constitute a contractual inclusion. If you prefer a particular language, confirm that both radio instructions and the preliminary explanation can use it.']]],
['pump-pressure','Kite inflation pressure: where to find the correct figure','Avoid universal pressure advice and identify the specification for your particular kite and pump.',[
['The number belongs to the model','Find the manufacturer’s guidance for your specific kite. Do not copy another unit’s pressure or turn informal advice into a rule for every model. Identification and the manual are the starting point for preparing equipment correctly.'],
['Check how pressure is measured','Pumps and gauges may display different units. Identify the unit used in the documentation and on the instrument. If the gauge is unreadable or its operation is uncertain, request a check instead of relying on a feel-based estimate.'],
['Inflation and condition are different issues','Pressure loss calls for investigating valves and structure rather than continually topping up without a diagnosis. Record when it happens and send that information to the repair service. An inspection may be necessary to distinguish apparently similar causes.'],
['During a lesson','Follow the instructor’s preparation procedure and ask where the specification appears. Learning to locate the correct figure is more useful than memorising an isolated number. Keep the manual with the rest of your records when using your own gear.']]],
['fins-footstraps','Fins and footstraps: checks before using a kiteboard','Prepare questions about fittings and adjustment without improvising changes to rental equipment.',[
['Identify the configuration','Board components should match the model and intended use. When collecting rental equipment, inspect the setup with the responsible person and report anything apparently loose or damaged. Do not assume a familiar configuration from another board transfers unchanged.'],
['Foot adjustment','Explain whether you can position your feet as instructed and whether the fit feels uncomfortable. Positioning is part of preparing the exercise. You should not silently tolerate a sizing problem simply to adapt to the equipment available.'],
['Do not replace screws by appearance','A component that seems to fit may not meet the specification. Use manufacturer references and documentation or a professional inspection for replacements. Report intended changes to rental equipment first so its recorded condition remains clear.'],
['What to send with an enquiry','Photograph the whole board and affected area, adding model and year if known. Explain whether you need adjustment, a spare part or inspection after an impact. This helps prepare the service and avoids purchasing accessories before identifying the problem.']]],
['equipment-record','Your kite equipment record: models, serial numbers and repairs','Organise information that helps with spare parts, servicing and equipment history.',[
['One entry per component','Record kite, bar, board and harness separately. Include brand, model, year and size where applicable. A setup bought on the same day may contain components from different seasons; separating them helps locate the correct manuals and spares.'],
['Keep readable identification','Store photographs of labels and serial numbers in a private folder. There is no need to post them publicly. Link each image to an available receipt so you can identify your unit without depending on the original listing’s commercial name.'],
['Record service work','After a repair, note date, affected area, replaced parts and workshop recommendations. Avoid vague labels such as “checked” if you do not know what was inspected. This history helps interpret later problems and describe condition when selling.'],
['Keep a travel copy accessible','Download manuals and service contacts so you do not depend on beach coverage. Share only necessary information with a workshop. An organised record reduces messaging but does not replace physical inspection when condition or compatibility needs assessment.']]],
['spare-parts-identification','How to request the correct kite spare part','Prepare photographs and references for valves, connectors and other components instead of buying by resemblance.',[
['Identify the equipment before the part','Start with the setup’s brand, model, year and size. Some spares differ between similarly named versions. If the reference is unknown, send a readable identification photograph rather than guessing the missing detail.'],
['Show context and detail','Include an overall view locating the area and a close-up of the component. An isolated image can conceal how it connects to the rest. Describe the observed symptom and when it occurs separately from your theory about the cause.'],
['Similar does not mean compatible','Two connectors may look alike but have different dimensions or specifications. Obtain supplier or manufacturer confirmation before purchasing. Also ask whether fitting requires technical work or additional parts so the repair budget is complete.'],
['Confirm availability and delivery','Request the exact reference, estimated lead time and installation conditions. Mention an upcoming flight before authorising work. Receiving a spare does not mean the equipment has already been checked or is ready to return to the water.']]],
['wet-gear-flight','Wet kite gear before a flight: planning your final day','Allow time for drying, packing and checking sports baggage rather than improvising on departure.',[
['Leave time after riding','A session immediately before an airport transfer limits equipment preparation time. Plan your last day with room to follow manufacturer cleaning and drying guidance. Do not assume your accommodation has an appropriate area available.'],
['Separate clothing and equipment','Organise compartments to keep moisture away from documents, electronics and dry clothing. Closing a bag does not dry its contents. If equipment must travel damp temporarily, plan where to open and care for it on arrival instead of leaving it forgotten inside.'],
['Check the final weight','The kit packed at home may return with extra accessories and moisture. Check dimensions, weight and conditions directly with the airline for your ticket. A baggage fee remembered from another trip is not a confirmed budget.'],
['Consider rental on the final day','If your own kit needs packing early, enquire about rental availability and requirements. Do not treat it as an automatic solution without confirming independence and suitable equipment. It can help with timing, but compare its cost within the whole trip plan.']]],
['sand-beach-storage','Where to leave kite gear between beach sessions','Ask about shade, space, custody and equipment care when planning a break between activities.',[
['A break needs organisation','Before entering the water, clarify where bags, shoes and personal items will stay. A meeting point does not imply a custody service. Distinguish the equipment preparation area from an authorised place for belongings during the lesson.'],
['Check equipment care requirements','Follow manufacturer guidance about exposure and storage. Avoid using a walkway as an equipment depot. Sand, heat and people moving around are factors for whoever organises the preparation area to consider.'],
['Do not assume continuous monitoring','Ask who has access, the hours available and any fee. Take only what is necessary for the activity in line with the instructions received. “Leave it there” does not clearly define responsibility or access at the end.'],
['Close the day properly','Count components and check for small accessories left between bags. Return rental equipment with the responsible person and report incidents. A joint check is preferable to leaving the setup behind without a recorded handover.']]],
['lost-board-plan','Losing sight of your kiteboard: what to agree before riding','Plan identification, communication and assistance limits instead of improvising a risky recovery.',[
['The plan starts beforehand','Ask how assistance is organised and which procedures the school teaches for local situations. Moving without the board is part of learning. An article cannot assess your position or prescribe a recovery manoeuvre for every circumstance.'],
['Identify the equipment','With rental gear, recognise the board you receive and record its condition with the operator. For your own board, keep photographs and references in your equipment record. Clear identification helps report a loss without confusion with other boards on the beach.'],
['Clarify responsibilities','Ask about assistance scope and loss or damage terms before accepting equipment. Do not assume every recovery is included in the price. Avoid adding improvised accessories as a solution without reviewing technical recommendations with a professional.'],
['Communicate useful information','If an incident occurs, follow the agreed plan and report the equipment and last observed location to the responsible person. Do not pursue an object at the expense of people’s safety. Priorities and next steps must reflect actual conditions rather than the board’s monetary value.']]]
];
