export default [
['first-kite-purchase','Primer equipo de kitesurf: qué decidir antes de comprar','Ordena nivel, lugar de uso, compatibilidad y mantenimiento antes de elegir tu primer conjunto.','gear','kite-size',0,[
['Compra para tu uso habitual','El equipo de unas vacaciones no define necesariamente lo que necesitas en casa. Describe dónde navegarás, con qué frecuencia y qué formación has completado. Lleva esa información a una evaluación profesional antes de escoger tamaño o modelo por una oferta atractiva.'],
['Piensa en un conjunto','Cometa, barra, líneas, tabla y arnés deben evaluarse como sistema. El precio de una cometa aislada no representa el coste de un conjunto utilizable. Pide verificar compatibilidad exacta y disponibilidad de repuestos, incluyendo las especificaciones del año y modelo.'],
['Prueba con un objetivo','Una prueba supervisada permite describir ajuste y sensaciones después de familiarizarte con el material. No necesitas buscar el modelo más avanzado: necesitas entender por qué corresponde a tu nivel y entorno. Compara también facilidad de inspección y soporte del fabricante.'],
['Calcula la propiedad completa','Añade bolsa, transporte, almacenamiento y mantenimiento al presupuesto. Conserva factura, identificación y manuales. Si todavía estás definiendo preferencias y autonomía, continuar aprendiendo con material seleccionado para la clase puede darte mejores criterios antes de comprometer una compra.']]],
['used-kite-inspection','Comprar un kite usado: documentación e inspección previa','Qué revisar con un especialista y qué pedir al vendedor antes de decidir por un equipo de segunda mano.','gear','kite-repair',0,[
['Identifica la unidad','Pide marca, modelo, año, talla y fotografías actuales del equipo completo. Comprueba que la identificación coincide entre anuncio y material. Pregunta por reparaciones y forma de almacenamiento; una descripción como “poco uso” aporta menos que un historial concreto y comprobable.'],
['Las fotos tienen límites','Imágenes de costuras, tejido, válvulas y conexiones ayudan a detectar preguntas, pero no certifican integridad. Una inspección presencial por alguien competente puede revelar problemas que no aparecen en una fotografía. No interpretes una apariencia limpia como garantía de vida útil.'],
['Incluye barra y repuestos','Si se vende un conjunto, identifica también la barra y sus líneas. Confirma compatibilidad con documentación del fabricante y disponibilidad de piezas. Un precio bajo pierde atractivo si necesitas sustituir componentes esenciales o no puedes obtener un repuesto específico.'],
['Decide con coste total','Suma inspección, reparaciones previstas y piezas faltantes antes de comparar con otras opciones. Solicita evidencia del estado y condiciones de la compraventa. Si no puedes aclarar procedencia, compatibilidad o daños, esa incertidumbre debe influir en la decisión y no esconderse detrás del descuento.']]],
['twin-tip-directional-foil','Twin-tip, tabla direccional y foil: diferencias para elegir clase','Comprende qué cambia entre tres tipos de tabla y por qué requieren objetivos de aprendizaje distintos.','comparison','kite-vs-wing',7,[
['Twin-tip','La tabla bidireccional está diseñada para navegar en ambos sentidos. Es una referencia habitual al hablar de iniciación en kite, aunque el material concreto lo selecciona la escuela. Su uso no significa que equilibrio, salidas y control de dirección se aprendan automáticamente.'],
['Tabla direccional','Tiene una orientación definida y se relaciona con modalidades y maniobras diferentes. La experiencia con twin-tip aporta contexto, pero la adaptación merece enseñanza específica. Al consultar, indica qué tabla utilizas y qué quieres aprender, en vez de pedir simplemente un nivel avanzado.'],
['Foil','El conjunto incorpora un mástil y superficies sumergidas que cambian la relación con el agua. Profundidad, material y control requieren una evaluación particular. No conviene elegir una sesión de foil solo porque visualmente parece una variación de la tabla que ya conoces.'],
['Elige el curso por la transición','Explica tu disciplina de origen y la de destino: por ejemplo, kite con twin-tip hacia kitefoil. Así la propuesta puede contemplar habilidades previas y nuevas. Comparar únicamente litros, centímetros o precio de las tablas deja fuera el propósito de la formación.']]],
['inflatable-vs-foil-kite','Cometa inflable y cometa foil: qué diferencia sus estructuras','Aclara la diferencia entre una cometa tipo foil y una tabla con hydrofoil antes de consultar material.','gear','kite-size',0,[
['Dos usos de la palabra foil','Foil puede nombrar un tipo de cometa o el conjunto sumergido de una tabla. Son elementos diferentes y no implican que se utilicen siempre juntos. Al pedir asesoría, envía el nombre completo o una fotografía para evitar una recomendación basada en un malentendido.'],
['Estructura de la cometa','Una cometa inflable utiliza elementos que se inflan para mantener su estructura. Una cometa tipo foil utiliza celdas y una construcción distinta. Esa diferencia influye en preparación, manejo y mantenimiento; no establece por sí sola que una opción sea adecuada para cualquier alumno.'],
['El uso previsto manda','Disciplina, entorno y experiencia deben preceder a la elección. No adoptes un modelo porque otra persona navega con poco viento en un vídeo: pueden cambiar peso, tabla, técnica y condiciones. Solicita una explicación sobre el sistema completo que vas a utilizar.'],
['Documentación específica','Consulta manual, sistemas y compatibilidad de la unidad concreta antes de cambiar de tipo. La experiencia con una construcción no elimina la familiarización con otra. Si tu objetivo es una primera clase, la pregunta útil es qué material selecciona la escuela para ese ejercicio y por qué.']]],
['harness-fit','Cómo comunicar si un arnés de kitesurf no te ajusta bien','Distingue talla, colocación y molestias para pedir una revisión antes de continuar la clase.','gear','first-lesson',1,[
['La talla escrita no basta','Dos arneses de la misma talla pueden ajustarse de forma diferente. El modelo y tu cuerpo influyen en la sensación. Durante la preparación pide que revisen el ajuste y explícales si una zona presiona o si el conjunto se mueve de una manera que no entiendes.'],
['Describe dónde y cuándo','Decir “me molesta” es un comienzo; señalar dónde ocurre y en qué momento ayuda más. Distingue incomodidad al colocarlo de un problema que aparece durante el ejercicio. No esperes al final para comunicar una molestia que afecta tu atención.'],
['Cambios con asistencia','Evita modificar conexiones por tu cuenta si todavía estás aprendiendo. Solicita una revisión al instructor antes de seguir. La familiarización con el conjunto incluye reconocer sus componentes y sistemas, no solo apretar una cinta hasta que parezca firme.'],
['Antes de comprar uno','Prueba el modelo con orientación adecuada y comprueba compatibilidad con el conjunto que usarás. Conserva la referencia exacta del que te resultó apropiado. Comprar únicamente por talla o por el que aparece en una fotografía no asegura reproducir ese ajuste.']]],
['bar-compatibility','¿Sirve cualquier barra para cualquier cometa?','Qué información de modelo, año, líneas y sistema debes reunir para verificar compatibilidad.','gear','kite-repair',0,[
['No basta contar las líneas','Compartir un número de líneas no demuestra compatibilidad. La configuración y el sistema del fabricante importan. Antes de combinar piezas, identifica cometa y barra con marca, modelo y año; una descripción genérica como “barra de cuatro líneas” deja información esencial sin resolver.'],
['Busca una confirmación documentada','Consulta el manual o soporte del fabricante para esa combinación específica. No extrapoles una recomendación de otra temporada o talla. Si no encuentras la información, lleva ambas referencias a un profesional que pueda revisar el conjunto antes de utilizarlo.'],
['Compatibilidad y estado son preguntas distintas','Una combinación admitida puede tener líneas desiguales, desgaste o piezas dañadas. La revisión de conservación sigue siendo necesaria. A la inversa, que una barra parezca nueva no demuestra que funcione correctamente con la cometa que quieres conectar.'],
['Al alquilar o reparar','Comunica si cambiaste alguna pieza y conserva su referencia. No mezcles componentes de dos alquileres para resolver una falta de material sin autorización. Para una consulta remota, envía identificación legible y fotos generales, evitando presentar una prueba de vuelo improvisada como método de validación.']]],
['helmet-vest-choice','Casco y chaleco en kitesurf: qué preguntar sobre protección','Entiende por qué ajuste, finalidad y especificación del equipo importan más que su aspecto.','gear','safety-checklist',1,[
['Cada elemento tiene una función','Un chaleco de impacto y un dispositivo de flotación no deben tratarse como equivalentes solo porque ambos se llevan sobre el torso. Lee la identificación del producto y pide explicación sobre su finalidad. La selección debe corresponder al ejercicio y al plan de la escuela.'],
['El ajuste requiere revisión','Una talla disponible no es automáticamente una talla apropiada. Antes de iniciar, comunica si el casco se mueve o si una prenda limita los movimientos necesarios. La comprobación debe realizarse con el conjunto que realmente usarás, incluido el arnés cuando corresponda.'],
['No deduzcas especificaciones de una foto','Forma, color o grosor no prueban una certificación. Al comprar, solicita documentación y referencia exacta del fabricante. Al reservar, pregunta qué elementos proporciona la escuela y qué debe llevar el alumno, sin asumir que todos los paquetes incluyen lo mismo.'],
['La protección no reemplaza el aprendizaje','Utilizar estos elementos no elimina la necesidad de enseñanza, evaluación del entorno y límites de práctica. Si una pieza está dañada o no puedes ajustarla, comunica el problema antes de continuar. La decisión no debe basarse en aguantar una incomodidad para no retrasar al grupo.']]],
['radio-lesson','Clases de kitesurf con radio: utilidad y límites','Qué acordar sobre comunicación, señales y funcionamiento cuando una escuela ofrece enseñanza por radio.','beginner','first-lesson',1,[
['Para qué puede servir','La radio permite transmitir indicaciones sin depender únicamente de la voz a distancia. Puede apoyar la enseñanza, pero su presencia no demuestra por sí sola mejor atención o menor número de alumnos. Pregunta cómo se integra en la organización de la sesión.'],
['Aclara el tipo de comunicación','Confirma si puedes responder o solo escuchar, y cómo comunicarás una dificultad. Una instrucción que no has entendido necesita un mecanismo de aclaración. La prueba inicial debe realizarse antes de alejarte, con el equipo colocado como se utilizará en el ejercicio.'],
['Si deja de oírse','Acuerda previamente qué hacer cuando se pierde comunicación y qué señales visuales se emplean. No inventes una respuesta en medio del ejercicio. Las instrucciones concretas deben proceder de quien dirige la sesión y conoce el área, el material y tu nivel.'],
['Qué confirmar en la reserva','Pregunta si el sistema forma parte de tu opción y si está disponible ese día. Una imagen publicitaria con radio no constituye una inclusión contractual. Si prefieres un idioma determinado, comprueba también que las indicaciones y la explicación previa pueden darse en ese idioma.']]],
['pump-pressure','Presión de inflado del kite: dónde encontrar el dato correcto','Evita usar una cifra universal y aprende a identificar la especificación de tu cometa y su bomba.','gear','saltwater-gear-care',0,[
['La cifra pertenece al modelo','Busca la indicación del fabricante para la cometa concreta. No copies la presión de una unidad distinta ni conviertas una recomendación informal en regla para todas. La identificación y el manual son el punto de partida para preparar correctamente el material.'],
['Comprueba cómo se mide','Las bombas y sus indicadores pueden mostrar unidades diferentes. Identifica qué unidad usa la documentación y cuál presenta el instrumento. Si no puedes leer el indicador o tienes dudas sobre su funcionamiento, solicita revisión antes de confiar en una estimación al tacto.'],
['Inflado y conservación no son lo mismo','Una pérdida de presión merece investigar estado de válvulas y estructura, no compensarla continuamente sin diagnóstico. Registra cuándo aparece y envía esa información al taller. El servicio de reparación puede necesitar una inspección para distinguir causas que se parecen desde fuera.'],
['Durante una clase','Deja que la preparación siga el procedimiento del instructor y pregunta dónde figura la especificación. Aprender a localizar el dato es más útil que memorizar una cifra aislada. Conserva el manual con el resto de documentación cuando empieces a utilizar material propio.']]],
['fins-footstraps','Quillas y footstraps: qué revisar antes de usar una tabla','Prepara una consulta sobre fijaciones y ajuste sin improvisar cambios en el material alquilado.','gear','rental-requirements',9,[
['Identifica la configuración','Las piezas de la tabla deben corresponder a su modelo y uso. Al recibir un alquiler, observa el conjunto con la persona responsable y comunica cualquier pieza que parezca floja o dañada. No des por hecho que una configuración conocida de otra tabla se traslada sin cambios.'],
['Ajuste de los pies','Explica si puedes colocar los pies como indica el instructor y si percibes un ajuste incómodo. La colocación forma parte de la preparación del ejercicio. No necesitas soportar un problema de talla para adaptarte al equipo disponible sin que nadie lo revise.'],
['No sustituyas tornillería a ojo','Una pieza que aparentemente encaja puede no ser la especificada. Para reemplazos utiliza referencias y documentación del fabricante o revisión profesional. En material alquilado, informa antes de modificar componentes; así se evita perder el seguimiento del estado entregado.'],
['Qué llevar a una consulta','Fotografía la tabla completa y la zona afectada, y añade modelo y año si los conoces. Explica si buscas ajuste, repuesto o revisión por un golpe. Esa diferencia permite preparar la atención y evita comprar accesorios antes de identificar el problema real.']]],
['equipment-record','Ficha de tu equipo: modelos, números de serie y reparaciones','Organiza la información que facilita repuestos, servicio técnico y seguimiento del material de kitesurf.','gear','saltwater-gear-care',0,[
['Una fila por componente','Registra cometa, barra, tabla y arnés por separado. Añade marca, modelo, año y talla cuando corresponda. Un conjunto comprado el mismo día puede contener componentes de temporadas distintas; distinguirlos ayuda a buscar manuales y repuestos correctos.'],
['Conserva identificaciones legibles','Guarda fotografías de etiquetas y números de serie en una carpeta privada. No es necesario publicarlos en redes. Vincula cada imagen con la factura o comprobante disponible para poder identificar tu unidad sin depender del nombre comercial del anuncio original.'],
['Anota intervenciones','Después de una reparación registra fecha, zona intervenida, piezas sustituidas y recomendaciones del taller. Evita etiquetas vagas como “revisado” si no recuerdas qué se comprobó. Ese historial facilita interpretar un problema posterior y describir el estado al vender.'],
['Ten una copia accesible en viaje','Lleva manuales y contactos de servicio descargados para no depender de cobertura en la playa. Comparte con el taller únicamente los datos necesarios. Una ficha ordenada ahorra mensajes, pero no sustituye la inspección física cuando hace falta evaluar conservación o compatibilidad.']]],
['spare-parts-identification','Cómo pedir el repuesto correcto para una cometa','Prepara fotos y referencias para consultar válvulas, conectores o piezas sin comprar por parecido.','repair','kite-repair',0,[
['Nombra el equipo antes de la pieza','Empieza por marca, modelo, año y talla del conjunto. Algunos repuestos cambian entre versiones con nombres parecidos. Si no conoces la referencia, envía una fotografía legible de la identificación en lugar de completar el dato por intuición.'],
['Fotografía contexto y detalle','Incluye una toma general que permita ubicar la zona y otra cercana del componente. Una imagen aislada puede ocultar cómo se conecta al resto. Describe el síntoma observado y cuándo ocurre, separándolo de tu hipótesis sobre la causa.'],
['Parecido no significa compatible','Dos conectores pueden verse similares y tener medidas o especificaciones diferentes. Solicita confirmación del proveedor o fabricante antes de comprar. También conviene preguntar si la sustitución requiere intervención técnica o piezas adicionales para no presupuestar una reparación incompleta.'],
['Confirma disponibilidad y entrega','Pide referencia exacta, plazo estimado y condiciones de instalación. Si tienes un vuelo próximo, informa la fecha antes de autorizar el trabajo. La recepción de un repuesto no significa que el equipo ya esté revisado ni listo para volver al agua.']]],
['wet-gear-flight','Equipo mojado antes del vuelo: cómo organizar el último día','Planifica secado, embalaje y peso del equipaje deportivo sin improvisar al salir hacia el aeropuerto.','travel','packing-list',12,[
['Deja margen después de navegar','Una sesión pegada al traslado al aeropuerto reduce el tiempo para revisar y preparar el material. Programa el último día con espacio para seguir las indicaciones de limpieza y secado del fabricante. No presupongas que el alojamiento tiene un área adecuada disponible.'],
['Separa ropa y equipo','Organiza compartimentos para no trasladar humedad a documentos, electrónica o prendas secas. Una bolsa cerrada no resuelve el secado; si transportas material húmedo temporalmente, prepara dónde abrirlo y atenderlo al llegar. Evita dejarlo olvidado dentro del equipaje.'],
['Revisa el peso final','El conjunto que preparaste en casa puede volver con accesorios adicionales y humedad. Comprueba dimensiones, peso y condiciones directamente con tu aerolínea para ese billete. No uses una tarifa de equipaje recordada de otro viaje como presupuesto confirmado.'],
['Considera alquilar el último día','Si necesitas empacar tu equipo con antelación, consulta disponibilidad de alquiler y sus requisitos. No lo reserves como solución automática sin haber confirmado autonomía y material. La alternativa permite organizar tiempos, pero su coste debe compararse con el plan completo del viaje.']]],
['sand-beach-storage','Dónde dejar el equipo entre sesiones en la playa','Preguntas sobre sombra, espacio, custodia y conservación para una pausa entre actividades.','gear','saltwater-gear-care',12,[
['Una pausa requiere organización','Antes de entrar al agua aclara dónde quedarán bolsa, calzado y objetos personales. Un punto de encuentro no implica servicio de custodia. Diferencia el espacio donde se prepara material del lugar autorizado para dejar pertenencias durante una sesión.'],
['Consulta las condiciones del material','Sigue las indicaciones del fabricante sobre exposición y almacenamiento. Evita utilizar una zona de paso como depósito de equipo. Arena, calor y movimiento de personas forman parte de lo que debe valorar quien organiza el área de preparación.'],
['No asumas vigilancia permanente','Pregunta quién tiene acceso al lugar, durante qué horario y si existe algún coste. Conserva contigo solo lo necesario para la actividad según las instrucciones recibidas. Una afirmación informal de “déjalo ahí” no aclara responsabilidad ni disponibilidad al terminar.'],
['Al cerrar el día','Cuenta componentes y revisa que no dejas accesorios pequeños entre las bolsas. Si el material es alquilado, realiza la devolución con el responsable y comunica incidencias. Esa revisión compartida es preferible a abandonar el conjunto sin constancia de entrega.']]],
['lost-board-plan','Si pierdes de vista la tabla: qué acordar antes de navegar','Prepara identificación, comunicación y límites de asistencia sin improvisar una recuperación arriesgada.','safety','safety-checklist',9,[
['El plan empieza antes','Consulta cómo se organiza la asistencia y qué procedimientos enseña la escuela para las situaciones del área. Las habilidades de desplazamiento sin tabla forman parte del aprendizaje. Una publicación no puede valorar tu posición ni indicar una maniobra de recuperación válida para cualquier circunstancia.'],
['Identifica el material','En un alquiler, reconoce la tabla que recibes y registra su estado con el responsable. Con material propio, conserva fotografías y referencias en tu ficha. Tener una identificación clara ayuda a comunicar una pérdida sin confundirla con otros equipos presentes en la playa.'],
['Aclara responsabilidades','Pregunta por el alcance de asistencia y por las condiciones comerciales ante pérdida o daño antes de aceptar el material. No supongas que el precio incluye cualquier recuperación. Tampoco incorpores accesorios improvisados como solución sin revisar recomendaciones técnicas con un profesional.'],
['Comunica información útil','Si ocurre una incidencia, sigue el plan acordado e informa al responsable de la última ubicación observada y del material. Evita perseguir un objeto poniendo a personas en una situación peor. La prioridad y los siguientes pasos deben responder a las condiciones reales, no al valor económico de la tabla.']]]
];
