export default [
['airport-transfer-kitebag','Traslado desde el aeropuerto con bolsa de kitesurf','Qué comunicar al reservar un vehículo para transportar personas y equipo deportivo en Cartagena.','travel','complete-guide',0,[
['Declara dimensiones y cantidad','Una reserva para dos pasajeros no describe una bolsa larga con tablas. Envía número de bultos y medidas exteriores al transportista. Añade maletas convencionales y acompañantes para que pueda confirmar capacidad real; no basta decir que llevas “equipaje deportivo”.'],
['Confirma el servicio concreto','Solicita punto de encuentro, identificación del vehículo, precio y destino. Si el vuelo cambia, utiliza el contacto acordado para actualizar la llegada. La reserva de una clase no implica que exista un traslado incluido desde el aeropuerto.'],
['Distingue alojamiento y playa','El lugar donde duermes puede ser distinto del punto de sesión. Organiza cada tramo con su destino preciso y contempla dónde dejarás el equipaje antes de la actividad. Llegar directamente con todas las maletas necesita coordinación adicional de espacio y custodia.'],
['Evita tiempos demasiado ajustados','Recogida de equipaje, desplazamiento y preparación consumen parte de la ventana disponible. No fijes una clase inmediatamente después de aterrizar sin explicar el plan. Pide una alternativa si el retraso del vuelo impide llegar al horario acordado.']]],
['no-car-kite-trip','Viaje de kitesurf a Cartagena sin alquilar carro','Organiza traslados por sesión y compara alojamiento según la logística real de tus días de playa.','travel','complete-guide',0,[
['Diseña los trayectos necesarios','Cuenta cuántas veces irás a la zona de práctica y desde dónde. Un alojamiento que parece económico puede añadir desplazamientos frecuentes. Compara coste total y tiempo disponible, sin asumir que una distancia corta en el mapa garantiza un traslado rápido.'],
['Cotiza ida y regreso','Pregunta por ambos trayectos, capacidad para equipo y flexibilidad del retorno. Si la sesión cambia de horario, necesitas saber cómo avisar. Evita depender de encontrar a última hora un vehículo con espacio adecuado para una tabla o una bolsa larga.'],
['Coordina el punto exacto','Usa el enlace de ubicación que confirme la escuela y distingue entrada a playa de punto de encuentro. Guarda un contacto y una descripción visual. Un nombre general como La Boquilla no define por sí solo dónde bajar del vehículo.'],
['Decide qué transportar','Si alquilas material en destino, verifica requisitos y disponibilidad antes de viajar sin el tuyo. Si llevas equipo, pregunta por almacenamiento en el alojamiento. Reducir los desplazamientos con bultos puede simplificar el viaje, pero no justifica asumir servicios que nadie confirmó.']]],
['remote-work-sessions','Teletrabajo y kitesurf: cómo organizar una semana en Cartagena','Reserva ventanas flexibles sin comprometer reuniones ni depender de un horario de viento garantizado.','travel','complete-guide',0,[
['Separa compromisos fijos y flexibles','Coloca primero reuniones y entregas que no puedes mover. Comparte con la escuela las ventanas restantes. El viento no se ajusta al calendario laboral, por lo que una semana con varias opciones ofrece más margen que una única hora libre al día.'],
['Calcula la ausencia completa','Incluye transporte, preparación y cambio de ropa además de la clase. No programes una videollamada justo al terminar en la playa. Si tienes una hora límite de regreso, indícala antes de confirmar el bloque para evitar expectativas incompatibles.'],
['Verifica dónde trabajarás','Comprueba conexión y condiciones del alojamiento directamente con quien lo ofrece. La playa o el punto de encuentro no deben asumirse como oficina, espacio para guardar portátil o lugar con alimentación eléctrica. Prepara una alternativa independiente de la actividad deportiva.'],
['Compra continuidad utilizable','Antes de elegir un paquete largo, consulta cómo se distribuyen horas y qué sucede si tus ventanas no coinciden con las condiciones. El menor precio por hora sirve poco si no puedes utilizarlo. Lleva un registro compartido de las sesiones efectivamente realizadas.']]],
['companion-beach-day','Qué hacer si acompañas a alguien a su clase de kitesurf','Organiza espera, encuentro y tiempos compartidos sin invadir el área de práctica.','travel','complete-guide',10,[
['Acompañar no equivale a participar','Aclara cuántas personas toman clase y cuántas solo acompañan. El instructor necesita concentrarse en los alumnos y el área de ejercicio. Pregunta dónde puede permanecer el acompañante sin cruzar líneas ni interferir con preparación o maniobras.'],
['Consulta comodidades reales','Sombra, asientos, baños y alimentos deben confirmarse para el punto concreto. No deduzcas esos servicios de una foto de playa. Si alguien necesita una condición particular para esperar, resuélvela antes de desplazarte.'],
['Planifica actividades separadas','Puedes consultar por SUP u otra actividad disponible, pero su horario y condiciones se evalúan por separado. No presupongas que un día adecuado para kite también lo sea para cualquier modalidad. Cada participante necesita su propia confirmación y punto de encuentro.'],
['Acuerda cómo reunirse','Define un lugar fuera del área de maniobra y un canal de contacto al finalizar. Las sesiones pueden ajustarse según condiciones; deja margen para comer o desplazarte después. Si el acompañante toma fotografías, debe hacerlo desde una posición autorizada.']]],
['shower-changing-storage','Baños, duchas y guardarropa: qué confirmar antes de ir a clase','Una ficha de servicios prácticos para organizar ropa, pertenencias y el plan después de la playa.','travel','packing-list',1,[
['No vienen implícitos con la actividad','Una clase en playa no garantiza vestuario, ducha o almacenamiento. Pregunta qué instalaciones están disponibles en el punto de encuentro elegido. Distingue las del operador de servicios cercanos prestados por terceros.'],
['Consulta acceso y horario','Si existe una instalación, confirma si está incluida, cuánto cuesta y hasta qué hora puede utilizarse. Esa información importa si terminas cerca del cierre o si cambias la sesión. No bases un traslado posterior en una ducha que aún no está confirmada.'],
['Prepara ropa y objetos','Lleva una muda y una bolsa apropiada para separar prendas húmedas. Reduce objetos de valor que no necesitas durante la clase. Si vas directamente a otra actividad, organiza previamente dónde cambiarte y cómo transportarás lo usado.'],
['Un mensaje que resuelve la logística','Indica fecha, número de personas y si necesitas baño, cambio de ropa o custodia. Pide respuesta separada para cada servicio. Así puedes completar lo que falte con el alojamiento sin confundir disponibilidad general de la zona con una inclusión de tu reserva.']]],
['accessible-lesson-planning','Necesidades de accesibilidad: cómo consultar una actividad de playa','Describe apoyos, desplazamientos y comunicación para recibir una respuesta concreta sobre la viabilidad de tu visita.','travel','first-lesson',1,[
['Describe tareas y apoyos','Explica qué necesitas para llegar, desplazarte, cambiarte y recibir instrucciones. Una descripción funcional ayuda más que una etiqueta general. Comparte solo la información personal necesaria para valorar la organización de la actividad.'],
['Pregunta por el recorrido completo','Solicita detalles del acceso desde el vehículo, superficie, distancia al encuentro e instalaciones. Una entrada accesible no demuestra que todo el recorrido lo sea. Pide que confirmen obstáculos y apoyos disponibles en el punto real de la sesión.'],
['La adaptación debe confirmarse','No asumas que el material o personal permiten cualquier adaptación. El operador debe evaluar la solicitud y explicar qué puede ofrecer. Si una pregunta implica aptitud médica, debe resolverse con el profesional correspondiente, sin sustituir esa valoración por una promesa comercial.'],
['Deja una alternativa acordada','Antes de desplazarte, guarda la respuesta sobre participación, acompañantes y cambios posibles. Si no se puede realizar la actividad propuesta, consulta otra experiencia compatible con lo confirmado. La decisión debe basarse en información específica, no en afirmar genéricamente que una actividad es para todos.']]],
['meeting-point-confirmation','Cómo confirmar el punto de encuentro de tu clase','Evita confundir una zona de playa con la ubicación exacta de la sesión y coordina tu llegada.','booking','book-whatsapp',1,[
['Una zona no es una dirección','La Boquilla identifica un área amplia. Solicita un enlace de ubicación y una referencia del punto donde te recibirá la persona responsable. Comprueba que corresponde a la sesión contratada y no simplemente a la ubicación comercial publicada en una ficha.'],
['Relaciona lugar y horario','Guarda fecha, hora de presentación y hora prevista de actividad. Pregunta si el lugar se confirma nuevamente cerca de la sesión según condiciones. Un mensaje antiguo puede dejar de representar la organización acordada para ese día.'],
['Comparte la ubicación con el transporte','Envía el enlace al conductor y aclara dónde puedes bajar con tus pertenencias. Si llevas material voluminoso, añade esa información. No necesitas compartir públicamente datos de la reserva para coordinar un traslado privado.'],
['Si no encuentras al responsable','Utiliza el contacto de la confirmación y espera instrucciones en un punto adecuado. Evita entrar por tu cuenta al área de preparación o tomar equipo suponiendo que pertenece a tu clase. Una identificación clara al llegar permite iniciar con orden.']]],
['weather-change-trip-plan','Si se aplaza tu sesión: cómo reorganizar el día de viaje','Separa la decisión meteorológica, las condiciones de reserva y tus otros compromisos para mantener opciones.','travel','wind-sources',0,[
['Confirma qué cambia','Una comunicación puede significar cambio de hora, de ejercicio o aplazamiento completo. Pide que aclaren cuál es la situación y cuándo habrá una nueva confirmación. No interpretes una previsión favorable para más tarde como una cita definitiva.'],
['Revisa tus límites de agenda','Indica hora de regreso, otros traslados y fecha de salida de Cartagena. Esos límites ayudan a proponer opciones utilizables. Si no puedes volver otro día, dilo antes de aceptar una reprogramación que solo funciona sobre el papel.'],
['No traslades el riesgo a otra actividad','Una alternativa en el agua necesita su propia evaluación. SUP, wing o foil no se convierten automáticamente en opciones adecuadas porque se detuvo una clase de kite. Organiza planes fuera del agua de forma independiente y con condiciones de reserva claras.'],
['Actualiza el registro','Solicita confirmación del tiempo realizado, saldo pendiente y acuerdo aplicable. Conserva los mensajes y evita basarte en políticas de otra empresa. Esta guía ayuda a ordenar decisiones; las condiciones concretas de devolución o cambio deben constar en tu reserva.']]],
['booking-receipt','Qué debe quedar en la confirmación de tu reserva','Reúne servicio, participantes, moneda, horario y condiciones en un comprobante fácil de consultar.','booking','book-whatsapp',0,[
['Identifica el servicio comprado','La confirmación debe permitir distinguir curso, refuerzo, alquiler o supervisión. Añade participantes y duración, indicando si las horas son individuales o compartidas. Un mensaje con solo una cifra no describe suficientemente lo que esperas recibir.'],
['Aclara el importe','Conserva moneda, total, anticipo si existe y saldo restante. Distingue tarifa por persona de tarifa por grupo. Si hay servicios externos, anótalos separados para no interpretar transporte o fotografía como incluidos en el importe principal.'],
['Guarda las condiciones acordadas','Incluye cómo se manejan cambios meteorológicos, cancelación personal y sesiones parciales. Pide aclarar cualquier punto que no entiendas antes de pagar. No necesitas una política imaginada a partir de otras webs: necesitas la que aplica a tu operación concreta.'],
['Lleva una copia accesible','Descarga o guarda el resumen con el punto de encuentro y contacto. Comparte datos de pago solo por los canales acordados y evita publicar comprobantes con información personal. Al terminar el paquete, verifica que el registro de horas coincide con las sesiones realizadas.']]],
['share-trip-costs','Viaje de kite entre amigos: cómo repartir los gastos','Separa enseñanza, equipo y gastos comunes para comparar un plan grupal sin confundir tarifas individuales.','travel','choose-course',6,[
['Distingue gastos comunes e individuales','Alojamiento o transporte pueden compartirse; una clase y su material pueden tener tarifa por persona. Organiza esas dos columnas antes de dividir un total. Así nadie asume que una reserva grupal aporta idénticas horas de práctica individual a todos.'],
['No fuerces el mismo curso','Personas con niveles distintos pueden necesitar formatos diferentes. Mantén comunes los traslados que encajen, pero solicita enseñanza según cada situación. Comprar el mismo paquete para simplificar cuentas puede dejar a alguien repitiendo contenidos o entrando a una actividad inadecuada.'],
['Documenta anticipos y saldos','Nombra quién contrató cada servicio y cuánto aportó cada persona. Guarda moneda y condiciones de cambio. Si alguien sale del plan, revisa lo acordado con el proveedor antes de redistribuir automáticamente un importe que quizá no sea recuperable.'],
['Reserva margen individual','Añade al presupuesto de cada participante posibles refuerzos o actividades opcionales. No los presentes como gastos obligatorios del grupo. Una cuenta transparente permite que cada persona decida qué necesita sin confundir convivencia del viaje con progresión deportiva idéntica.']]]
];
