export default {
 'complete-guide':['Viaggio kite a Cartagena: itinerario e alloggio','Organizza tre, cinque o sette giorni con trasferimenti, finestre di pratica e tempo per gli accompagnatori.',
 ['Conta i giorni utilizzabili','Arrivare venerdì sera e partire domenica a mezzogiorno lascia un solo giorno completo. Inserisci prima voli e impegni fissi. Con tre giorni conserva una seconda finestra; con cinque o sette alterna pratica, riposo e visite senza presumere autonomia finale.'],
 ['Scegliere la base','Confronta La Boquilla con le zone vicine alle visite, includendo i trasferimenti nel costo. Chiedi spazio per asciugare e custodire l’attrezzatura. Al conducente serve un punto preciso, non soltanto il nome della spiaggia.'],
 ['Budget e viaggio internazionale','Separa lezioni, noleggio, pasti, trasporto e bagaglio sportivo. Dall’Europa o dagli USA controlla ogni compagnia operativa. Verifica i requisiti ufficiali d’ingresso e chiedi all’assicuratore conferma scritta della copertura dell’attività.'],
 ['Viaggiare insieme','Una coppia può condividere i trasporti ma avere obiettivi diversi. Prevedi ombra e attività per chi non pratica, oltre al tempo per asciugare il materiale e raggiungere l’aeroporto.']],
 'best-time':['Quando fare kite a Cartagena: guida alle stagioni','Scegli le date con il contesto climatico e verifica poi ogni sessione con informazioni aggiornate.',
 ['Clima e previsione','Le tendenze di molti anni aiutano il viaggio, non confermano un pomeriggio. Consulta la climatologia CIOH-DIMAR e poi bollettini recenti e valutazione locale.'],
 ['Da dicembre a marzo','Dicembre è generalmente l’inizio della fase secca, con possibili transizioni. Gennaio, febbraio e marzo appartengono al periodo tradizionalmente più asciutto. Non significa vento quotidiano o condizioni sempre adatte ai principianti.'],
 ['Aprile e mesi piovosi','Osserva la transizione di aprile. Da maggio a novembre conta soprattutto la finestra concreta e gli avvisi. Pioggia stagionale non significa calma permanente; una raffica associata a una nube non invita a uscire.'],
 ['Confrontare soggiorni','Conta i giorni completi e la flessibilità. Chiedi come gestire ore non svolte se il volo impedisce il recupero. Non attribuiamo percentuali di giorni navigabili senza dati e metodo definiti.']],
 'first-lesson':['Prima lezione di kite: preparazione e aspettative','Scopri obiettivi iniziali, abbigliamento e domande su nuoto, età e timori.',
 ['Controllo prima della tavola','La lezione presenta area, materiale e segnali. Secondo le condizioni si parte da terra e dal controllo del kite. Finire senza navigare non è un fallimento: conta ciò che sai ripetere.'],
 ['Descrivi il punto di partenza','Spiega quanto sei a tuo agio nuotando in mare e quali timori hai. Concorda un segnale di pausa. Il giubbotto non sostituisce competenza acquatica. Per minori verifica criteri, accompagnatore e materiale adeguato.'],
 ['Prepara l’abbigliamento','Scegli costume stabile e protezione solare comoda sotto il trapezio. Togli accessori che si impigliano. Porta acqua, asciugamano e cambio; chiedi quali calzature servono all’ingresso.'],
 ['Registra i progressi','Distingui esercizi con indicazioni da quelli ripetuti autonomamente. Annota il prossimo obiettivo oltre alle ore pagate. Chiedi cosa devi dimostrare prima del passaggio successivo.']],
 'how-long':['Quanto serve per imparare kite: tappe e autonomia','Distingui ore di corso, water start e navigazione indipendente.',
 ['Le ore non sono un livello','Otto ore descrivono insegnamento, non certificano autonomia. Continuità, condizioni ed esperienza cambiano il risultato. Confronta valutazione e pratica effettiva oltre alla durata.'],
 ['Controllo e water start','Il controllo precede movimento in acqua e recupero tavola. Il water start combina kite, corpo e tavola. Una breve partenza non dimostra ancora arresto e direzione costanti.'],
 ['Tornare al punto previsto','Risalire il vento è un obiettivo distinto, con velocità controllata e spazio rispetto agli altri. Non compensare la deriva allontanandoti dalla costa. I livelli IKO descrivono capacità, non risultati garantiti per ora.'],
 ['La prossima sessione','Annota abilità, aiuto richiesto e difficoltà principale. Dopo una pausa prevedi rivalutazione o ripasso mirato. Un noleggiatore può verificare la capacità attuale anche con una formazione precedente.']],
 'safety-checklist':['Sicurezza kite: ambiente, attrezzatura e rientro','Organizza il controllo prima della sessione intorno a spazio, comunicazione e ritorno.',
 ['Valuta anche la deriva','Individua persone, ostacoli, linee e uscite sottovento. Un decollo libero può condurre a una zona difficile. Fatti spiegare dove finiresti senza avanzamento.'],
 ['Conosci il sistema di oggi','Controlla il materiale e impara lo sgancio con aiuto competente e manuale. Linee danneggiate o pezzi dubbi richiedono verifica. Concorda segnali chiari: un gesto ambiguo non autorizza il lancio.'],
 ['Condividi e rientra','Lascia liberi i passaggi e impara le precedenze. Avere precedenza non elimina evitare collisioni. Definisci rientro e assistenza. L’autosoccorso si pratica con istruttore, non soltanto leggendo una sequenza.'],
 ['Fermarsi in tempo','Prepara acqua, ombra e pause. Interrompi se cambiano condizioni o non capisci un’istruzione. Segnala rientro e anomalie. Questa lista non certifica idoneità alla navigazione.']],
 'la-boquilla-guide':['La Boquilla e altri spot: scegliere la spiaggia','Confronta accesso e assistenza a La Boquilla, Manzanillo, Las Velas e Salinas del Rey.',
 ['La Boquilla','Usa il punto della scuola e conferma il settore giornaliero. Una spiaggia lunga ha più accessi. Identifica area didattica e uscita; una foto calma non prova condizioni adatte ai principianti.'],
 ['Manzanillo del Mar','A nord di Cartagena occorre organizzare accesso e ritorno. Verifica quale servizio e materiale saranno presenti. Le strutture della scuola non seguono automaticamente uno spostamento.'],
 ['Las Velas','Chiedi posizione precisa e valutazione locale. Considera altri usi della spiaggia e corridoi d’ingresso. Un punto sulla mappa non conferma vento, spazio libero o assistenza.'],
 ['Salinas del Rey','È nell’Atlántico, fuori Cartagena: pianifica un’escursione propria con trasporto e coordinamento locale. Confronta viaggio totale, livello, servizio e alternativa meteo. Cambiare spiaggia non garantisce condizioni migliori.']],
 'packing-list':['Bagagli kite: cosa portare e preparazione del volo','Controlla oggetti da spiaggia, peso, misure e regole di ogni compagnia operativa.',
 ['Solo ciò che serve','Separa effetti personali, materiale e conferme. Verifica l’attrezzatura inclusa prima di imbarcare la tua. Fotografa modello, misura e stato. Porta acqua, protezione solare, asciugamano e cambio asciutto.'],
 ['Ogni tratta conta','Tariffa e compagnia operativa stabiliscono le condizioni. Misura ruote e protezioni e pesa tutti gli accessori. Definire la sacca da golf non modifica le regole del materiale effettivo.'],
 ['Proteggi i componenti','Segui il manuale e separa parti rigide dal tessuto. Attrezzi, colle e batterie possono essere soggetti a restrizioni: verifica con compagnia e autorità aeroportuale. Prenota un veicolo abbastanza capiente.'],
 ['Ritiro e piccoli ricambi','Conserva la ricevuta e segnala danni secondo la procedura della compagnia. Porta soltanto ricambi compatibili e conosciuti; un kit non sostituisce la diagnosi di danni strutturali.']],
 'kite-size':['Misura del kite: vento, peso, tavola e modello','Raccogli i dati del materiale e del praticante prima di scegliere la superficie.',
 ['La superficie non basta','Kite della stessa misura possono avere campi diversi. Consulta modello, anno e barra compatibile. Una tabella universale non può valere per tutte le persone.'],
 ['Informazioni necessarie','Indica peso, livello, tavola e intervallo del produttore, oltre a vento osservato, raffiche e direzione sulla costa. Copiare un altro rider lascia variabili sconosciute.'],
 ['Variabilità e utilizzo','Una media può nascondere raffiche; una misura lontana non descrive necessariamente la spiaggia. Il limite superiore del produttore non è un obiettivo per principianti. Rivaluta anche passando da twin-tip a foil.'],
 ['Una domanda completa','Invia caratteristiche e capacità attuali, poi conferma sul posto. Nel noleggio chiarisci cosa accade se manca un insieme adatto. La decisione corretta può essere rinunciare alla sessione.']],
 'book-whatsapp':['Prenotare kite: dati, pagamento e cambi meteo','Conferma servizio, totale e condizioni di modifica per iscritto prima di pagare.',
 ['Una richiesta utile','Indica date, partenza dalla città, partecipanti, lingua e necessità di materiale o transfer. Descrivi capacità concrete, come water start senza rientro, anziché un livello generico.'],
 ['Capire la conferma','Una risposta automatica non riserva un posto. Richiedi servizio, durata, valuta, partecipanti e totale. Distingui data riservata e orario operativo; conserva il canale concordato per i cambi.'],
 ['Separare i casi','Controlla destinatario e saldo. Chiedi di cancellazione personale, sospensione meteo e sessione parziale, soprattutto se il volo impedisce recuperi. Questa pagina non stabilisce acconti o rimborsi.'],
 ['Riconfermare','Contatta in anticipo per gruppi o lingue specifiche. Al momento concordato verifica luogo, ora e referente. Non inviare documenti d’identità o dati finanziari nella richiesta iniziale.']],
 'choose-course':['Quale corso kite scegliere secondo le tue capacità?','Confronta introduzione, progressione, ripasso e lezione condivisa con obiettivi concreti.',
 ['Descrivi ciò che sai fare','Specifica controllo, recupero tavola, water start e ritorno. Un vecchio corso non definisce la capacità attuale. Scegli basi, continuità o una difficoltà precisa.'],
 ['Lezione privata','Chiedi se istruttore e materiale sono dedicati e come si distribuiscono spiegazione, pratica e pause. Privata non significa ogni minuto in acqua.'],
 ['Pratica condivisa','Verifica numero di allievi, kite e istruttori. La durata indica il blocco o il tempo individuale? Livelli diversi possono richiedere esercizi distinti.'],
 ['Servizi confrontabili','Noleggio non significa insegnamento. Se servono indicazioni per fermarti o rientrare, chiedi valutazione. Confronta obiettivo, rapporto didattico, lingua, materiale e ore non effettuate.']],
 'rental-requirements':['Noleggio kite: autonomia e consegna del materiale','Prepara la valutazione e confronta noleggio locale con trasporto della tua attrezzatura.',
 ['Capacità attuale','Spiega quando hai navigato, con quali condizioni e materiale. Un attestato aiuta, ma può servire verifica locale. Dichiara abilità ancora mancanti.'],
 ['Definisci l’assistenza','Chiarisci lancio, atterraggio, sorveglianza, incidenti, zona e rientro. Il noleggio non include automaticamente soccorso o lezioni. Per guida continua confronta un servizio supervisionato.'],
 ['Documenta la consegna','Fotografa danni esistenti e controlla comandi e compatibilità. Chiarisci garanzia, responsabilità, inizio del tempo e cambi di vento o assenza di materiale adatto.'],
 ['Noleggiare o portare','Confronta bagaglio e trasporto con disponibilità, asciugatura e custodia. Verifica componenti misti propri e noleggiati. Riconsegna al responsabile e chiedi chiusura del servizio e della garanzia.']],
 'wind-sources':['Leggere il vento: orari, raffiche e direzione','Interpreta la finestra prevista e discuti la sessione concreta con la scuola.',
 ['Identifica i dati','Controlla luogo, emissione, periodo, fuso e unità. Nodi, chilometri orari e metri al secondo differiscono. Invia il collegamento, non un numero ritagliato.'],
 ['Oltre la media','La raffica è un picco; la media riassume un intervallo. Non esiste soglia unica per principianti. Comprendi le frecce e riferisci la direzione al tratto di costa.'],
 ['Mattina o pomeriggio','Non ogni pomeriggio migliora. Esamina l’intero blocco, cambi e avvisi ufficiali. Gli alisei spiegano un contesto regionale; DIMAR, modelli e osservazioni locali si completano.'],
 ['Se non si può uscire','Consulta le alternative della prenotazione. Esercizi a terra devono essere utili e concordati, senza sostituire automaticamente il tempo pattuito. Chiarisci il caso di partenza senza altro giorno disponibile.']],
 'kite-vs-wing':['Kitesurf o wing foil: materiale e apprendimento','Confronta trazione, tavola e obiettivi iniziali prima di scegliere una prova.',
 ['Due sistemi','Il kite è collegato alla barra tramite linee; il wing si tiene in mano. Preparazione e coordinazione cambiano. Nessuna disciplina è priva di rischi o garantisce autonomia nell’altra.'],
 ['La prima tavola','Il kite iniziale usa spesso twin-tip. Il wing foil unisce ala, tavola e foil, ma può iniziare con esercizi adattati. Chiedi il materiale effettivo della prima lezione.'],
 ['Spazio e capacità','Le linee richiedono spazio di montaggio e utilizzo; il foil impone attenzione alla profondità. Esperienza nel surf aiuta alcuni gesti senza sostituire le procedure specifiche.'],
 ['Scegli un obiettivo','Confronta istruttore, durata e meta didattica, non facilità universale. Chi conosce una disciplina deve comunque imparare comandi e sistemi del nuovo materiale.']],
 'kite-repair':['Kite danneggiato: diagnosi, riparazione o sostituzione','Descrivi perdita di pressione, strappi e linee per comprendere l’intervento proposto.',
 ['Parti dal sintomo','Invia marca, modello, anno, misura e storia, con foto generali e dettagli in scala. Una perdita dopo un intervallo è più utile di una sostituzione del bladder presunta.'],
 ['Danni differenti','La valvola visibile può non essere l’origine della perdita. Tessuto, cucitura e rinforzo richiedono valutazioni diverse. Evita colla improvvisata e altro utilizzo; coprire uno strappo non prova resistenza.'],
 ['Linee e barra','Il sistema opera come insieme. Nodi inventati o pezzi simili possono cambiarne il comportamento. Sospendi l’uso e chiedi riferimenti compatibili nel preventivo.'],
 ['Capire la restituzione','Richiedi diagnosi, ricambi, prezzo, tempi e limiti residui. L’ispezione fisica può cambiare la proposta. Conserva controlli e storia; consulta la disponibilità nella pagina del servizio.']],
 'saltwater-gear-care':['Cura del kite: asciugatura, custodia e usura','Organizza il dopo-sessione seguendo il manuale di ogni componente.',
 ['Il manuale corretto','Kite, barra, linee, tavola e trapezio possono richiedere cure diverse. Identifica il modello prima di applicare prodotti. La manutenzione preventiva non ripara componenti di sicurezza danneggiati.'],
 ['Sabbia e umidità','Evita superfici abrasive e non strofinare sabbia nel tessuto. Asciuga secondo il manuale senza sole inutile. Riapri all’arrivo il materiale trasportato bagnato.'],
 ['Osserva e conserva','Cerca tagli, abrasione e modifiche ai collegamenti. Non correggere lunghezze con nodi improvvisati. Conserva asciutto, al riparo da calore eccessivo, luce e spigoli.'],
 ['Storia e revisione','Registra incidenti e riparazioni. Le foto aiutano il confronto senza certificare lo stato. Perdite, cuciture aperte o dubbi sullo sgancio richiedono diagnosi, non semplice pulizia.']]
};
