export default {
 'complete-guide':['Viagem de kite a Cartagena: roteiro e hospedagem','Organize três, cinco ou sete dias com deslocamentos, janelas de prática e tempo para acompanhantes.',
 ['Conte os dias úteis','Chegar sexta à noite e sair domingo ao meio-dia deixa apenas um dia inteiro. Coloque voos e compromissos fixos antes das aulas. Em três dias, preserve outra janela possível; em cinco ou sete, alterne prática, descanso e passeios sem prometer autonomia.'],
 ['Escolha a base','Compare La Boquilla com a proximidade dos passeios urbanos, somando os traslados à diária. Pergunte por espaço para secar e guardar equipamento. Envie ao motorista o ponto exato: o nome da praia não identifica a escola.'],
 ['Planeje o custo completo','Separe aulas, aluguel, refeições, transporte e bagagem esportiva. Em viagens dos EUA ou da Europa, confira a empresa que opera cada conexão. Verifique requisitos oficiais de entrada e peça à seguradora confirmação escrita sobre a atividade e suas exclusões.'],
 ['Viaje acompanhado','Casais podem dividir transporte e precisar de metas diferentes. Organize sombra e atividades para quem não pratica. Reserve tempo para secar material e chegar ao aeroporto após a última sessão.']],
 'best-time':['Melhor época para kite em Cartagena: guia sazonal','Escolha datas com contexto climático e flexibilidade; confirme cada sessão com informação atual.',
 ['Clima não é previsão diária','Padrões de muitos anos ajudam a planejar a viagem, mas não confirmam sua tarde reservada. Use a climatologia CIOH-DIMAR para contexto e boletins recentes para a sessão.'],
 ['De dezembro a março','Dezembro costuma marcar o início do período seco, ainda com transição. Janeiro, fevereiro e março pertencem à fase tradicionalmente mais seca. Isso não garante vento diário nem condições adequadas a iniciantes.'],
 ['Abril e meses mais chuvosos','Observe a transição em abril. De maio a novembro, valorize janelas específicas e avisos meteorológicos. Chuva sazonal não significa ausência permanente de vento; uma rajada de nuvem não é motivo para entrar.'],
 ['Compare estadias','Conte dias completos e flexibilidade antes de escolher um mês popular. Pergunte sobre horas não realizadas quando o voo impede remarcar. Não apresentamos percentuais de dias navegáveis sem dados e método definidos.']],
 'first-lesson':['Primeira aula de kite: preparação e expectativas','Entenda os primeiros objetivos, a roupa, a natação e como conversar sobre receios.',
 ['Controle antes da prancha','A introdução apresenta área, equipamento e sinais. Conforme as condições, começa com exercícios em terra e controle da pipa. Terminar sem velejar na prancha não é fracasso; importa o que você consegue repetir.'],
 ['Explique seu ponto de partida','Conte sua familiaridade com natação no mar e experiências anteriores. Descreva receios e combine um sinal de pausa. Colete não substitui competência aquática. Para crianças, confirme critérios, responsável e equipamento adequado.'],
 ['Prepare a roupa','Use roupa de banho firme e proteção solar confortável sob o trapézio. Retire acessórios que possam prender. Leve água, toalha e troca seca; pergunte pelo calçado apropriado ao acesso.'],
 ['Registre o aprendizado','Separe o que realizou com instruções do que repetiu sozinho. Anote a próxima habilidade, além das horas pagas. Pergunte o que precisa demonstrar antes de avançar.']],
 'how-long':['Tempo para aprender kite: etapas e autonomia','Diferencie horas de curso, primeiros water starts e navegação independente.',
 ['Horas não são certificação','Oito horas descrevem ensino, não um nível garantido. Continuidade, condições e experiência influenciam o resultado. Compare também avaliação e prática efetiva.'],
 ['Controle e water start','O controle antecede deslocamento na água e recuperação da prancha. O water start combina pipa, corpo e prancha. Uma saída breve ainda não demonstra parada e direção consistentes.'],
 ['Voltar ao ponto previsto','Orçar é uma meta própria. Velocidade, parada e distância de outras pessoas fazem parte dela. Não compense deriva afastando-se mais da costa. Os níveis IKO descrevem competências, sem garantir resultado por hora.'],
 ['Prepare a próxima sessão','Registre habilidade, ajuda necessária e dificuldade principal. Após uma pausa, faça reavaliação ou reforço específico. Um locador pode conferir sua capacidade atual mesmo com registro de formação.']],
 'safety-checklist':['Segurança no kite: local, equipamento e retorno','Organize a conversa anterior à sessão sobre ambiente, comandos, comunicação e volta.',
 ['Observe a possível deriva','Identifique pessoas, obstáculos, linhas e saídas, inclusive a sotavento. Um lançamento livre pode levar a uma área difícil. Peça explicação do trajeto caso você deixe de avançar.'],
 ['Conheça o conjunto utilizado','Confira o material e aprenda a liberação com ajuda competente e manual. Linha danificada ou peça duvidosa exige revisão. Combine sinais claros; gesto ambíguo não autoriza lançamento.'],
 ['Compartilhe a praia','Mantenha passagens livres e aprenda regras de preferência. Ter preferência não elimina evitar colisões. Defina retorno e apoio. Autorresgate é habilidade praticada com instrutor, não substituída por uma sequência escrita.'],
 ['Saiba encerrar','Planeje água, sombra e pausas. Pare quando as condições mudarem ou a instrução não estiver clara. Avise que voltou e comunique anomalias. Esta lista não certifica aptidão para navegar.']],
 'la-boquilla-guide':['La Boquilla e outros spots: escolher o local','Compare acesso e suporte em La Boquilla, Manzanillo, Las Velas e Salinas del Rey.',
 ['La Boquilla','Use o ponto da escola e confirme o setor do dia. Uma praia longa tem diversos acessos. Identifique área de ensino e saída; foto de água calma não garante condição para iniciante.'],
 ['Manzanillo del Mar','Ao norte de Cartagena, exige organizar acesso e retorno. Confirme serviço e material que estarão disponíveis. As instalações da escola não acompanham automaticamente uma mudança de spot.'],
 ['Las Velas','Peça localização precisa e avaliação local. Entenda a convivência com outros usos da praia e corredores de entrada. Um marcador no mapa não confirma vento, espaço ou assistência.'],
 ['Salinas del Rey','Fica no Atlántico, fora de Cartagena: planeje uma excursão própria, com transporte e coordenação local. Compare viagem completa, nível, serviço e alternativa meteorológica. Mudar de praia não garante melhores condições.']],
 'packing-list':['Bagagem de kite: lista e preparação do voo','Confira itens de praia, peso, medidas e regras de cada companhia operadora.',
 ['Leve o necessário','Separe itens pessoais, equipamento e confirmações. Confira o material incluído na aula antes de despachar o seu. Fotografe modelo, tamanho e estado. Leve água, proteção solar, toalha e roupa seca.'],
 ['Confira cada trecho','Tarifa e empresa operadora definem condições de bagagem. Meça com rodas e proteções e pese todos os acessórios. Chamar a bolsa de golfe não altera as regras do equipamento transportado.'],
 ['Proteja e identifique','Siga instruções de embalagem e isole peças rígidas do tecido. Ferramentas, colas e baterias podem ter restrições: consulte companhia e autoridade aeroportuária. Reserve veículo compatível com o comprimento da bolsa.'],
 ['Recebimento e reparos','Guarde comprovante e siga o procedimento da companhia ao detectar danos. Um kit de viagem deve conter peças compatíveis e conhecidas; não substitui diagnóstico de dano estrutural ou em linhas.']],
 'kite-size':['Tamanho de kite: vento, peso, prancha e modelo','Reúna dados do conjunto e do praticante antes de escolher a área da pipa.',
 ['Área não explica tudo','Pipas da mesma área podem ter faixas diferentes. Consulte modelo, ano e barra compatível. Uma tabela universal não atende todas as pessoas e pranchas.'],
 ['Informe os dados úteis','Descreva peso, nível, prancha e faixa do fabricante, além de vento observado, rajadas e direção na costa. Copiar a pipa de outra pessoa deixa variáveis desconhecidas.'],
 ['Considere a variação','Uma média pode esconder rajadas fortes. Medição distante não representa necessariamente a praia. O limite superior do fabricante não é meta de iniciante; trocar twin-tip por foil também exige reavaliação.'],
 ['Pergunte de forma completa','Envie dados do equipamento e habilidades atuais, confirmando a escolha no local. No aluguel, esclareça o que acontece se não houver conjunto apropriado. A decisão adequada pode ser não sair.']],
 'book-whatsapp':['Reservar kite: dados, pagamento e mudanças por clima','Confirme serviço, valor total e condições de alteração por escrito antes de pagar.',
 ['Envie uma solicitação útil','Informe datas, saída da cidade, participantes, idioma e necessidade de material ou traslado. Descreva habilidades concretas, como water start sem retorno, em vez de um nível genérico.'],
 ['Entenda a confirmação','Resposta automática não garante vaga. Solicite serviço, duração, moeda, pessoas e total. Separe data reservada de horário operacional e guarde o canal combinado para alterações.'],
 ['Separe os casos','Confira destinatário do pagamento e saldo. Pergunte sobre cancelamento pessoal, suspensão por clima e sessão parcial, principalmente quando o voo impede remarcar. Este artigo não cria sinal ou política de devolução.'],
 ['Reconfirme perto da sessão','Contate cedo para grupos ou idioma específico. No momento combinado, confirme local, hora e responsável. Não envie documentos de identidade nem dados financeiros na consulta inicial.']],
 'choose-course':['Qual curso de kite escolher pelo seu nível real?','Compare introdução, progressão, reforço e aula compartilhada por habilidades e metas.',
 ['Descreva suas habilidades','Indique controle, recuperação da prancha, water start e retorno. Curso antigo não define capacidade atual. Escolha base inicial, continuidade ou trabalho de uma dificuldade identificada.'],
 ['Entenda a aula privada','Pergunte se instrutor e material são dedicados a você e como se dividem explicação, prática e pausas. Privada não significa que todo minuto será dentro da água.'],
 ['Entenda os turnos','Na compartilhada, confira alunos, pipas e instrutores. A duração é do bloco ou da prática individual? Pessoas com níveis diferentes podem precisar de tarefas distintas.'],
 ['Compare o mesmo serviço','Aluguel não equivale a aula. Se precisa de orientações para parar ou voltar, peça avaliação. Compare objetivo, proporção, idioma, material e tratamento de horas não realizadas.']],
 'rental-requirements':['Aluguel de kite: autonomia e entrega do material','Prepare a avaliação e compare aluguel local com transporte do seu equipamento.',
 ['Capacidade atual','Conte quando navegou, em quais condições e com qual conjunto. Registro de curso ajuda, mas pode haver avaliação local. Avise sobre habilidades ainda ausentes antes de receber material.'],
 ['Defina o apoio','Esclareça lançamento, pouso, vigilância, incidências, área e devolução. Aluguel não inclui automaticamente ensino ou resgate. Para orientação contínua, compare serviço supervisionado.'],
 ['Documente a entrega','Fotografe danos existentes e confira comandos e compatibilidade. Esclareça garantia, responsabilidade, início da cobrança e mudança de vento ou falta de equipamento adequado.'],
 ['Alugar ou levar','Compare bagagem e transporte com disponibilidade, secagem e armazenamento. Verifique compatibilidade ao misturar peças próprias e alugadas. Devolva ao responsável e confirme encerramento e garantia.']],
 'wind-sources':['Ler a previsão de kite: horário, rajadas e direção','Interprete a janela prevista e discuta a sessão concreta com a escola.',
 ['Identifique a informação','Confira local, emissão, período, fuso e unidades. Nós, quilômetros por hora e metros por segundo são diferentes. Envie o link em vez de um número recortado.'],
 ['Leia além da média','Rajada é pico; média resume um intervalo. Não há limite único para todos os iniciantes. Entenda o sentido das setas e relacione a direção ao trecho de costa.'],
 ['Manhã ou tarde','Nem toda tarde melhora. Observe todo o bloco, mudanças e avisos oficiais. Alísios explicam contexto regional; DIMAR, modelos e observação local têm funções complementares.'],
 ['Quando não é possível','Consulte alternativas acordadas na reserva. Exercícios em terra precisam ser úteis e aceitos, sem substituir automaticamente o tempo contratado. Esclareça o caso em que sua partida impede outra data.']],
 'kite-vs-wing':['Kitesurf ou wing foil: equipamento e aprendizagem','Compare tração, prancha e objetivo inicial antes de escolher uma experiência.',
 ['Dois sistemas','No kite, linhas conectam a pipa à barra; o wing é segurado pelas mãos. Montagem e coordenação mudam. Nenhuma modalidade é isenta de risco nem gera autonomia automática na outra.'],
 ['A primeira prancha','Kite inicial costuma usar twin-tip. Wing foil reúne asa, prancha e foil, podendo começar com exercícios adaptados. Pergunte qual conjunto será utilizado na primeira aula.'],
 ['Espaço e habilidade','Linhas precisam de área de montagem e operação; foil exige considerar profundidade. Experiência em surf ou vela ajuda alguns movimentos, mas não substitui procedimentos do equipamento.'],
 ['Escolha uma meta','Compare instrutor, duração e objetivo pedagógico, não uma promessa de facilidade universal. Quem já pratica uma modalidade ainda precisa conhecer os comandos e sistemas da outra.']],
 'kite-repair':['Pipa danificada: diagnóstico, reparo ou troca','Descreva perda de pressão, rasgos e linhas para entender o alcance de uma intervenção.',
 ['Comece pelo sintoma','Informe marca, modelo, ano, tamanho e histórico, com fotos gerais e detalhes com escala. Perda de pressão após determinado tempo explica mais que presumir troca do bladder.'],
 ['Diferencie os danos','A válvula visível pode não ser a origem da fuga. Tecido, costura e reforço exigem avaliações diferentes. Evite cola improvisada e uso adicional; cobrir um rasgo não prova resistência.'],
 ['Linhas e barra','O conjunto funciona integrado. Nós inventados ou peças parecidas podem alterar comportamento. Retire componentes duvidosos de uso e peça referências compatíveis no orçamento.'],
 ['Entenda a devolução','Solicite diagnóstico, peças, preço, prazo e limitações restantes. Inspeção física pode alterar a proposta. Registre verificações e histórico; consulte disponibilidade na página do serviço.']],
 'saltwater-gear-care':['Cuidado do kite: secagem, armazenamento e desgaste','Organize a rotina após navegar com o manual de cada componente.',
 ['Use o manual correto','Pipa, barra, linhas, prancha e trapézio podem exigir cuidados diferentes. Identifique o modelo antes de aplicar produtos. Manutenção preventiva não recupera peça de segurança danificada.'],
 ['Areia e umidade','Evite superfícies abrasivas e não esfregue areia no tecido. Seque conforme o manual, sem sol desnecessário. Reabra o equipamento ao chegar se precisou transportá-lo molhado.'],
 ['Observe e guarde','Procure cortes, abrasão e mudanças nas conexões. Não corrija comprimento de linha com nó improvisado. Guarde seco, protegido de calor excessivo, luz direta e bordas rígidas.'],
 ['Histórico e revisão','Anote incidentes e reparos. Fotografias ajudam a acompanhar, mas não certificam o estado. Fuga de ar, costura aberta ou dúvida na liberação exigem diagnóstico; limpeza não resolve esses problemas.']]
};
