// Publication requires a confirmed legal profile. Business terms are versioned.
export const version='2026-09-15';
export const title='Términos y condiciones | Kite Cartagena';
export const description='Condiciones de reserva, pagos, cancelación, clima, seguridad, alquiler de equipos, responsabilidad, privacidad y reclamaciones de Kite Cartagena.';
export const sections=[
['alcance','1. Alcance y responsable de la comercialización',[
'Estas condiciones regulan las consultas, reservas y servicios comercializados mediante Kite Cartagena por el responsable identificado al inicio de esta página. Comprenden cursos de kitesurf, clases de refuerzo, actividades de kitefoil y wing, alquiler de equipos, supervisión, SUP, downwind, fotografía y servicios complementarios que se incluyan expresamente en una confirmación.',
'Kite Cartagena es la identificación comercial utilizada en este sitio. La confirmación indicará quién comercializa, quién ejecuta cada actividad y, cuando corresponda, el prestador del transporte u otro servicio complementario. La intervención de un tercero no elimina las obligaciones de información, calidad, garantía o responsabilidad que la ley atribuya al comercializador o al prestador.',
'Una página informativa, un artículo del blog o una conversación preliminar no asignan por sí solos un instructor, una embarcación, un horario ni un cupo. La relación concreta se integra con la oferta comunicada, la confirmación, estas condiciones entregadas antes de contratar y las normas imperativas aplicables.'] ],
['aceptacion','2. Información previa, aceptación y prueba de la reserva',[
'Antes de solicitar un pago se facilitarán el servicio seleccionado, participantes, duración, precio total, moneda, inclusiones, exclusiones, condiciones de cambio y los datos del responsable. El cliente podrá revisar y corregir la información, preguntar por cláusulas que no comprenda y conservar una copia. El mero acceso a la web no constituye aceptación de una reserva, de riesgos deportivos ni de publicidad.',
'La aceptación deberá ser expresa y quedar asociada a la versión de condiciones y al resumen de la reserva, mediante un mensaje o mecanismo equivalente. No se presumirá por silencio. El pago acredita una operación económica, pero no sustituye por sí solo la entrega previa de condiciones ni permite añadir después cargos o restricciones que no fueron informados.',
'El cliente debe conservar el resumen y comunicar errores de nombres, fechas, nivel o cantidad de participantes. El comercializador conservará la trazabilidad que corresponda. Si existe contradicción entre información vinculante, se aplicará la legislación de consumo y la interpretación que legalmente proceda, sin usar estas condiciones para retirar beneficios expresamente ofrecidos.'] ],
['precios','3. Precios, moneda y cotizaciones',[
'Salvo indicación expresa distinta, los precios del catálogo se presentan en pesos colombianos, COP. Se distinguirá tarifa por persona, grupo, hora, paquete o sesión. El total informado antes de aceptar deberá incluir impuestos y cargos obligatorios aplicables; los extras opcionales requieren aceptación separada. Una tarifa grupal no implica una hora individual completa para cada integrante cuando existe rotación informada.',
'Las calculadoras son estimaciones basadas en las selecciones y cifras introducidas. Transporte, alimentación o gastos agregados por el usuario no constituyen una cotización de terceros. Las variaciones de cambio o comisiones de una entidad financiera externa deben distinguirse del precio cobrado por nosotros y explicarse cuando sean conocidas.',
'Una cotización puede tener una vigencia comunicada por escrito. Los cambios de precios rigen para nuevas contrataciones y no modifican retroactivamente reservas confirmadas. Un posible error de publicación se atenderá de manera transparente conforme a las reglas de información y publicidad; no concede una facultad general para desconocer unilateralmente una oferta o pago.'] ],
['pagos','4. Anticipos, saldos y canales de pago',[
'El importe y vencimiento de cualquier anticipo se comunicarán para la reserva concreta. No existe un porcentaje universal implícito en estas condiciones. El saldo y su fecha de pago deben aparecer en el resumen. Un anticipo se imputa al precio del servicio y no se transforma automáticamente en una suma no reembolsable.',
'Solo se realizarán pagos a los canales y beneficiarios confirmados por el contacto oficial. No solicitamos contraseñas bancarias, códigos de verificación ni fotografías de tarjetas completas. Ante instrucciones de pago diferentes o sospechosas, el cliente debe verificar el cambio antes de transferir. El tratamiento de una operación fraudulenta se resolverá según los hechos y derechos aplicables, no mediante una exoneración automática.',
'Se facilitará comprobante y factura cuando corresponda. Un cupo condicionado a un anticipo dentro de un plazo puede liberarse si ese requisito no se cumple y así se informó previamente. Si se recibe dinero cuando ya no existe disponibilidad, se informará y se ofrecerá una alternativa aceptable o la devolución correspondiente; no se impondrá un bono.'] ],
['inclusiones','5. Qué incluye y qué no incluye cada servicio',[
'La confirmación debe identificar material, enseñanza, número de participantes por instructor, tiempo y apoyos incluidos. Fotografías con equipos, radios, embarcaciones o instalaciones no sustituyen esa lista. Traslados, duchas, baños, custodia, alimentos, seguros, certificaciones, imágenes y repuestos se incluyen únicamente cuando la oferta contratada lo indique.',
'El tipo, talla y configuración del material se seleccionan según ejercicio, disponibilidad y evaluación operativa, respetando lo ofrecido. Una sustitución debe mantener la idoneidad y calidad contratadas. Una modificación sustancial del servicio, nivel de atención o alcance requiere información y acuerdo; no basta invocar disponibilidad para entregar una prestación inferior.',
'Las actividades adicionales se cotizan antes de ejecutarse. No se cobrarán por sorpresa ampliaciones de tiempo, acompañantes, daños presuntos ni servicios que el usuario no haya solicitado o autorizado conforme al contrato.'] ],
['duracion','6. Duración de clases, paquetes y tiempo efectivamente prestado',[
'La preparación, explicación, ajuste de equipo, ejercicios y revisión final pueden formar parte de la enseñanza cuando así se describa. Se aclarará desde qué momento empieza el cómputo. En clases compartidas se informará la organización de turnos y observación. No se presentará una hora de grupo como una hora individual simultánea si ese no es el formato.',
'Los paquetes pueden distribuirse en varias jornadas acordadas. Al terminar cada sesión se registrará el tiempo prestado y el saldo pendiente. Las esperas por imposibilidad meteorológica o falta de recursos del prestador no se contarán como enseñanza salvo que se realice un contenido alternativo equivalente aceptado por el alumno.',
'Si se necesita prorrogar una sesión, debe acordarse precio y disponibilidad antes de iniciar la extensión. Las discrepancias sobre tiempo se revisarán con mensajes y registros disponibles; el cómputo del prestador no es una prueba irrefutable frente al consumidor.'] ],
['clima','7. Viento, estado del mar y decisiones de seguridad',[
'El viento, las rachas, el oleaje, las tormentas, la visibilidad, la profundidad, las restricciones de autoridad y la ocupación del área pueden impedir o modificar una actividad. Los promedios estacionales y pronósticos no garantizan condiciones diarias. La decisión operativa corresponde al responsable de la actividad, quien evaluará lugar, material y participantes y comunicará el motivo del cambio.',
'Ningún cliente puede exigir entrar al agua, aumentar potencia, realizar saltos, seguir una ruta o continuar un ejercicio contra una instrucción justificada de seguridad. A su vez, esa facultad no autoriza cambios arbitrarios, discriminación ni cobros por prestaciones inexistentes.',
'Cuando no sea posible prestar total o parcialmente el servicio por condiciones, se propondrá reprogramación o alternativa adecuada. Si no se alcanza un acuerdo, se devolverá el valor de la parte no prestada, sin penalización por cancelación del cliente. No se obligará a aceptar un bono, otra disciplina o una fecha posterior a su estancia. En paquetes, la valoración del saldo utilizará el precio contratado, sin recalcular retroactivamente las horas disfrutadas a una tarifa mayor.'] ],
['cambios-cliente','8. Cambios y cancelaciones solicitados por el cliente',[
'La solicitud debe enviarse por el correo o WhatsApp oficial indicando referencia, fecha y cambio deseado. Se tendrá en cuenta la recepción verificable del mensaje, no la hora en que el equipo lo lea. Las horas de referencia son las de Cartagena de Indias, Colombia. Un cambio no queda confirmado hasta acordar disponibilidad y alcance.',
'Como política comercial general, una cancelación comunicada al menos cuarenta y ocho horas antes del inicio permite devolver el valor no prestado sin penalidad propia. Solo podrán descontarse compromisos individualizados con terceros si fueron informados y aceptados antes de contratar, son realmente no recuperables, están soportados y resultan legalmente exigibles. No se introducirán gastos administrativos genéricos después de la cancelación.',
'Con menor anticipación, se procurará reprogramar. Cualquier cargo por cancelación tardía debe haberse explicado con importe o método de cálculo en la confirmación, ser proporcional y respetar la ley; esta página no establece una pérdida automática del total. Si no se informó y aceptó un cargo aplicable, no se inventará posteriormente. El retracto, el incumplimiento del proveedor y demás derechos legales prevalecen sobre esta política comercial.',
'Una sustitución de participante exige informar al responsable y comprobar requisitos de participación. Enfermedad, fuerza mayor o dificultades graves se analizarán de buena fe con información pertinente, sin exigir historia clínica completa ni documentos innecesarios.'] ],
['inasistencia','9. Llegadas tarde, inasistencia y abandono voluntario',[
'El cliente debe llegar al punto y hora confirmados y avisar de retrasos. Se valorará si todavía puede recibir la actividad sin omitir instrucciones esenciales ni afectar sesiones posteriores. Un retraso no autoriza a saltarse la preparación de seguridad. La reprogramación depende de disponibilidad y debe confirmarse.',
'Cuando se configure una no presentación imputable al usuario en un servicio turístico y se hayan comunicado y aceptado previamente sus consecuencias, se podrá aplicar el cargo del veinte por ciento del precio total previsto para ese supuesto en el artículo 65 de la Ley 300 de 1996. Si se pactó válidamente una modalidad de retención del anticipo permitida por esa norma, será alternativa, no acumulativa al cargo. No se presumirá ese pacto ni se impondrá por defecto una retención del cien por ciento.',
'No se tratará como inasistencia una cancelación por el prestador, falta de condiciones, punto de encuentro incorrectamente comunicado o ejercicio válido de un derecho legal. El abandono voluntario tras comenzar se revisará según tiempo prestado, motivo y condiciones aceptadas. No se aplicará una pérdida automática de todo el paquete, ni se duplicará un cobro por la misma consecuencia.'] ],
['retracto','10. Derecho de retracto',[
'Cuando proceda por la modalidad de contratación y las circunstancias del servicio, el consumidor puede ejercer el retracto dentro de los cinco días hábiles siguientes a la celebración del contrato de prestación de servicios. Debe comunicar su decisión por un canal oficial con información suficiente para identificar la reserva. No necesita justificar un cambio de opinión ni aceptar un bono en sustitución del dinero.',
'Se aplican las excepciones legales, incluida la prestación de servicios que haya comenzado con acuerdo del consumidor en los términos de la normativa. Una fecha próxima o la sola publicación de estas condiciones no constituyen por sí mismas renuncia al retracto. Si el servicio comenzará dentro de ese plazo, se explicará la situación y se documentará el acuerdo de inicio, sin casillas premarcadas ni aceptaciones ficticias.',
'Cuando el retracto sea procedente, se devolverá íntegramente el dinero sin descuentos o retenciones por esa decisión, dentro del plazo legal máximo de quince días calendario y conforme a los requisitos legalmente aplicables para efectuar la devolución. Se solicitarán únicamente los datos necesarios. No se retrasará el inicio del plazo mediante una aprobación interna discrecional.'] ],
['reversion','11. Reversión de pagos y devoluciones',[
'Cuando la operación y el medio de pago estén comprendidos en el régimen de reversión, se respetarán las causales legales, como fraude, operación no solicitada, falta de entrega o prestación, o falta de correspondencia con lo adquirido, según el caso. El consumidor deberá presentar la reclamación al proveedor y notificar al emisor del instrumento de pago dentro del plazo legal de cinco días hábiles contado desde el hecho que corresponda a la causal. Este mecanismo es distinto del retracto y de una cancelación comercial.',
'Las devoluciones se tramitarán por el medio original o por otro acordado que permita verificar al destinatario. No se pedirán claves ni códigos de autenticación. La identidad del titular y los datos de devolución se revisarán con medidas proporcionales. Las demoras de un tercero financiero se comunicarán y gestionarán, sin convertirlas en una exoneración general del cumplimiento de plazos.',
'Los reembolsos comerciales de valores no prestados se gestionarán en un máximo de quince días calendario desde que se determine el importe y se disponga de la información imprescindible para pagarlo, sin perjuicio de un plazo legal que deba empezar antes o resultar más favorable. Se entregará el soporte de la devolución y se explicará cualquier diferencia admisible.'] ],
['incumplimiento','12. Cancelación o incumplimiento del prestador',[
'Si una falta de personal, equipo, cupo u otra causa atribuible al prestador impide cumplir lo ofrecido, se informará oportunamente y se respetarán las opciones y remedios del consumidor conforme a la ley. La agencia no podrá sustituir unilateralmente una prestación por otra inferior ni imponer créditos de uso futuro.',
'Una reserva confirmada obliga en los términos ofrecidos. La participación de operadores aliados no elimina la atención de la reclamación ni permite enviar al cliente de un proveedor a otro sin respuesta. Se identificarán los responsables del servicio y se tramitará una solución sin perjuicio de las responsabilidades que legalmente correspondan.'] ],
['riesgos','13. Naturaleza deportiva y reconocimiento informado de riesgos',[
'El kitesurf, kitefoil, wing, SUP y las travesías son actividades acuáticas y al aire libre con riesgos, incluso bajo instrucción. Pueden producirse caídas, golpes, cortes, colisiones, enredos, pérdida de equipo, fatiga, desplazamiento involuntario, exposición ambiental, inmersión y lesiones graves. La magnitud depende del ejercicio, condiciones, material y participantes.',
'Antes de practicar se explicarán los riesgos relevantes, límites del área, comunicación, procedimientos y elementos necesarios. El participante debe preguntar si algo no resulta claro y puede comunicar que no desea continuar. Reconocer riesgos inherentes no equivale a aceptar material defectuoso, instrucción negligente o incumplimiento de obligaciones del prestador.',
'No se garantiza aprender una maniobra, navegar de forma independiente, alcanzar una certificación ni obtener un resultado físico en un número fijo de horas. Sí deben prestarse la enseñanza y los recursos contratados con la diligencia e idoneidad exigibles. Los artículos del blog no son instrucciones suficientes para practicar por cuenta propia.'] ],
['participacion','14. Información del participante y requisitos de acceso',[
'El participante debe comunicar con veracidad experiencia, habilidades y limitaciones relevantes para la actividad, incluyendo necesidades de comunicación o ajuste de material. No debe presentarse como autónomo para acceder a un alquiler si todavía necesita instrucciones continuas. La información solicitada será pertinente y proporcional al servicio.',
'Cuando una condición requiera valoración médica, esta corresponde a un profesional competente; la escuela no emite diagnósticos ni garantiza aptitud por una conversación comercial. No se exigirá divulgar información sensible innecesaria ni se presumirá consentimiento para tratarla por haber consultado precios.',
'La participación puede condicionarse a una evaluación práctica y disponibilidad de material adecuado. Se explicarán las razones objetivas de una negativa o adaptación y se considerarán ajustes razonables. Una diferencia de edad, nacionalidad, discapacidad u otra condición no justifica por sí sola un trato arbitrario.'] ],
['menores','15. Participación de menores',[
'Un menor requiere evaluación de la actividad y autorización de quien ejerza legalmente su representación, así como la presencia o disponibilidad de esa persona en las condiciones informadas. La admisión depende de capacidad para seguir instrucciones, condiciones y equipo apropiado, no de una edad encontrada en otra página.',
'El acompañante no debe interferir con las indicaciones técnicas ni dejar a otros menores bajo custodia del instructor sin un servicio expresamente acordado. La autorización del representante no elimina los derechos del menor ni exonera al prestador por actos u omisiones de los que deba responder.',
'Las imágenes o datos de menores requieren tratamiento especialmente cuidadoso, autorización válida cuando corresponda y respeto de su interés superior. Una reserva familiar no autoriza automáticamente uso publicitario de fotografías.'] ],
['conducta','16. Conducta, suspensión y cuidado del entorno',[
'Se deben seguir las instrucciones, respetar áreas y turnos, usar correctamente el equipo y comunicar incidentes. Se prohíben conductas agresivas, acoso, manipulación no autorizada del material, invasión de zonas restringidas y participación bajo efectos que comprometan el control o la comprensión, incluidos alcohol o sustancias que produzcan esa alteración.',
'El responsable podrá detener una práctica ante un peligro concreto o incumplimiento de indicaciones, explicando y registrando lo ocurrido cuando sea posible. La liquidación económica se revisará según el servicio prestado, causa y condiciones válidamente acordadas; la suspensión no equivale automáticamente a perder cualquier derecho de devolución.',
'Se deben respetar comunidades locales, fauna, vegetación, residuos y restricciones de las autoridades. Está prohibida cualquier forma de explotación o violencia contra niños, niñas y adolescentes. Los hechos que corresponda reportar se pondrán en conocimiento de la autoridad competente.'] ],
['alquiler','17. Alquiler, entrega y devolución de equipos',[
'El alquiler sin enseñanza requiere cumplir la evaluación y condiciones informadas. El arrendatario recibe un inventario con identificación, accesorios y estado, que podrá revisar y comentar antes de aceptar. Debe verificar ajuste y funcionamiento con el responsable y reportar anomalías antes de usar el equipo o tan pronto se adviertan.',
'No se permite ceder, subarrendar, modificar, reparar ni llevar el equipo fuera de las zonas y horarios autorizados sin acuerdo. La elección de condiciones, rutas o maniobras debe respetar los límites comunicados. Un alquiler no incluye clase, rescate ilimitado, custodia ni supervisión continua salvo contratación expresa.',
'La devolución se realizará en el punto y horario acordados, mediante revisión conjunta cuando sea posible. Se registrarán componentes y novedades. Una ampliación requiere disponibilidad y precio aceptado; el retraso no autoriza cargos indefinidos o no informados. Los objetos olvidados se gestionarán con el contacto disponible y una custodia razonable.'] ],
['danos','18. Pérdidas, daños y depósitos de garantía',[
'El desgaste normal, un defecto previo o una falla imputable al material o al prestador no se trasladan al usuario. Si se considera que existe daño o pérdida atribuible al participante, se documentarán estado de entrega, incidente, relación causal y valor reclamado, permitiéndole aportar su versión. No se presumirá culpabilidad por el solo hecho de haber utilizado el equipo.',
'La cuantificación considerará reparación razonable o, cuando corresponda, valor justificado de reposición teniendo en cuenta estado y antigüedad, sin cobrar simultáneamente reparación y reposición del mismo componente ni generar enriquecimiento injustificado. La inexistencia de un precio de repuesto en la web no concede libertad para fijar cargos arbitrarios.',
'Cualquier depósito de garantía debe tener monto, finalidad, forma de custodia y plazo de liberación informados antes de contratar. No se retendrá automáticamente por una diferencia discutida ni se cargarán tarjetas sin autorización válida. No se retendrán documentos originales de identidad como garantía. La resolución de desacuerdos conserva las vías legales de ambas partes.'] ],
['supervision','19. Supervisión, asistencia y travesías',[
'Se debe diferenciar enseñanza activa, supervisión de práctica y ayuda puntual en playa. La confirmación indicará alcance, duración, comunicación y recursos disponibles. Ayuda en el despegue no significa vigilancia individual continua; una tarifa de supervisión no incluye necesariamente un instructor dedicado durante todo el recorrido.',
'Para downwind y actividades con salida y llegada distintas se informarán ruta prevista, requisitos, acompañamiento, traslados y condiciones de modificación. El recorrido puede adaptarse por seguridad de forma justificada, con explicación de sus consecuencias sobre la prestación. No se garantiza una embarcación de apoyo o un recurso de rescate si no está contratado, ni puede omitirse un recurso exigido por la normativa o por la operación segura.',
'El participante debe conocer las señales y el plan antes de salir. La asistencia no reemplaza habilidades exigidas para contratar y tampoco libera al prestador de cumplir el apoyo ofrecido.'] ],
['reparacion','20. Diagnósticos, reparaciones y custodia técnica',[
'Una valoración por fotografías es preliminar. Antes de intervenir se identificará el equipo, el problema observado, el alcance, precio o presupuesto y plazo estimado. Trabajos adicionales requieren autorización; una autorización de inspección no implica autorización ilimitada para sustituir componentes.',
'Se explicará si la reparación es técnicamente viable, sus límites y la garantía legal aplicable. No se prometerá dejar cualquier equipo como nuevo ni se excluirá de forma general la garantía del servicio. El cliente debe comunicar reparaciones previas conocidas y recoger el material de acuerdo con el aviso de terminación.',
'El almacenamiento posterior o transporte adicional solo generará cargos si fueron informados y aceptados, son razonables y legalmente proceden. El silencio del propietario no transfiere la propiedad del equipo al taller ni autoriza su disposición inmediata.'] ],
['terceros','21. Transporte, pertenencias y proveedores externos',[
'El transporte se incluye únicamente cuando figure en la reserva y debe identificar condiciones y proveedor. El cliente informará pasajeros y dimensiones de equipaje deportivo. Los tiempos estimados no sustituyen un margen de regreso al aeropuerto, barco u otra conexión; se comunicarán las restricciones de agenda antes de contratar.',
'Baños, duchas, sombra y custodia deben confirmarse para el punto concreto. Si se recibe un bien expresamente en custodia, se aplican las obligaciones correspondientes; no se puede negar esa responsabilidad mediante un aviso genérico. Se recomienda no llevar objetos innecesarios a la actividad y acordar dónde permanecerán.',
'Una recomendación editorial de un tercero no equivale a contratarlo. Cuando nosotros vendamos o integremos su servicio en un paquete, se mantendrán las obligaciones que legalmente correspondan. No se excluye de forma general la responsabilidad por la mera participación de un aliado.'] ],
['emergencias','22. Emergencias y seguros',[
'Se solicitará un contacto de emergencia cuando sea pertinente y se explicará cómo avisar al responsable. Ante un incidente se priorizará detener la actividad y activar asistencia adecuada. Los servicios públicos de emergencia en Colombia pueden contactarse mediante el 123, sin que ello sustituya el plan de respuesta del operador.',
'Solo se anunciará una póliza incluida cuando pueda identificarse aseguradora, cobertura, vigencia, exclusiones y procedimiento. El RNT, una credencial deportiva o la palabra supervisión no constituyen por sí mismos una póliza. Se recomienda comprobar si el seguro personal cubre la modalidad y lugar de práctica.',
'Tener o no un seguro personal no modifica las responsabilidades legales de quien presta el servicio. No se exigirá una renuncia general a reclamar por lesiones como condición para recibir asistencia. Los gastos y coberturas se determinarán según contratos, circunstancias y normativa aplicable.'] ],
['responsabilidad','23. Responsabilidades y límites de estas condiciones',[
'Cada parte responde por los incumplimientos y daños que le sean jurídicamente atribuibles. El usuario debe actuar con cuidado, respetar las instrucciones y aportar información veraz; el comercializador y el prestador deben cumplir información, idoneidad, seguridad, garantía y demás obligaciones a su cargo.',
'Estas condiciones no excluyen responsabilidad por dolo, culpa grave, negligencia imputable, material defectuoso o cualquier supuesto cuya limitación esté prohibida. No establecen un techo general equivalente al precio pagado para lesiones o daños, ni obligan al consumidor a indemnizar indiscriminadamente cualquier reclamación de terceros.',
'Los eventos de fuerza mayor o caso fortuito se analizarán según sus requisitos y efectos legales; no basta llamar así a cualquier dificultad operativa. Las medidas de mitigación, información, liquidación de prestaciones y devoluciones se resolverán conforme a los hechos y a los derechos aplicables.'] ],
['imagenes','24. Fotografía, vídeo y uso de imagen',[
'Una sesión fotográfica debe precisar entrega, selección, edición, formato y plazo. Las condiciones de luz y la actividad pueden influir en el resultado, pero no eliminan las obligaciones expresamente asumidas. Las imágenes generadas o representativas del sitio no prueban instalaciones, equipo disponible ni resultados individuales.',
'La compra de una experiencia o la presencia en la playa no autorizan utilizar la imagen identificable del cliente en publicidad. El uso promocional requerirá autorización separada, libre e informada sobre finalidades y canales. Negarse no impide contratar la actividad. Para menores se aplican las garantías y autorizaciones correspondientes.',
'El cliente puede comunicar solicitudes sobre su imagen por los canales oficiales. El análisis técnico de vídeos y el uso publicitario son finalidades diferentes. Los permisos que el cliente otorgue a una red social no sustituyen el consentimiento que corresponda al negocio.'] ],
['datos','25. Datos personales y comunicaciones',[
'El responsable identificado en esta página atenderá solicitudes sobre los datos que trate para consultas, reservas, facturación, coordinación, seguridad y reclamaciones. Se solicitará autorización cuando la ley la exija, informando previamente finalidad, derechos y canales. Navegar por el sitio o pedir un precio no autoriza campañas promocionales indefinidas.',
'Se limitará la información a lo necesario. Datos sensibles, incluidos salud, requieren las garantías y autorización explícita que correspondan; no es obligatorio responder preguntas sensibles salvo que exista una base legal aplicable. No deben enviarse historias clínicas, contraseñas o documentos completos por un chat abierto cuando no sean indispensables.',
'Los datos necesarios para ejecutar una reserva podrán compartirse con el operador o proveedor identificado, con finalidad y salvaguardas adecuadas. No se venden listados de clientes. WhatsApp, correo y otros proveedores tienen sus propias condiciones; su uso no elimina nuestras obligaciones sobre los datos que controlamos.',
'El titular puede conocer, actualizar, rectificar y solicitar prueba de autorización, así como pedir supresión o revocación cuando proceda y presentar quejas ante la SIC tras el trámite aplicable. Las consultas se atenderán en los plazos legales de diez días hábiles y los reclamos en quince días hábiles; las ampliaciones legalmente permitidas deberán informarse con su motivo. La conservación se limitará a finalidades justificadas y obligaciones legales. El envío de publicidad requiere una decisión separada y podrá cancelarse por el mismo canal.'] ],
['web','26. Uso del sitio, contenidos y enlaces',[
'El sitio puede contener guías, comparadores y enlaces informativos. Se procura mantenerlos actualizados, pero la práctica deportiva exige evaluación local y la información comercial debe concretarse en la oferta. Ninguna guía sustituye enseñanza presencial, asesoría médica o una instrucción del responsable durante una emergencia.',
'Los contenidos y marcas están sujetos a los derechos de sus titulares. Se permite consultarlos para preparar una reserva; una reutilización comercial o reproducción extensa requiere autorización cuando la ley lo exija. No se autoriza interferir con el funcionamiento, suplantar identidades o enviar contenido malicioso.',
'Los enlaces oficiales permiten ampliar información; no implican que la autoridad o la organización citada avale el negocio. Una falla técnica del sitio no invalida una reserva confirmada ni elimina las vías de contacto y reclamación disponibles.'] ],
['reclamaciones','27. Peticiones, quejas y reclamaciones',[
'El cliente puede escribir al correo o WhatsApp de atención indicados al inicio, incluyendo nombre, referencia si la tiene, descripción y solución solicitada. Se admitirán soportes pertinentes y se confirmará recepción. No se exigirá un formato exclusivo, una publicación favorable o retirar una reseña como condición de atención.',
'Las reclamaciones directas de consumo se responderán dentro de los quince días hábiles legalmente previstos, con explicación y soportes cuando correspondan. Solicitar información pertinente no permite prolongar arbitrariamente un plazo legal. Una reclamación no extingue ni suspende automáticamente otros términos que deba observar el interesado.',
'El consumidor conserva el derecho de acudir a la Superintendencia de Industria y Comercio o a la autoridad o juez competente. Una conversación comercial no constituye conciliación obligatoria ni impone arbitraje o un fuero exclusivo que limite derechos. Se recomienda conservar comunicaciones y comprobantes.'] ],
['vigencia','28. Ley aplicable, actualizaciones y conservación',[
'Se aplican las normas colombianas pertinentes sobre consumo, turismo, comercio electrónico, datos personales y las reglas de la actividad, sin perjuicio de derechos imperativos que correspondan al consumidor. Si una estipulación no puede aplicarse legalmente, se interpretará o sustituirá conforme a la ley sin eliminar las demás disposiciones válidas.',
'La versión publicada y su fecha se identifican en esta página. Los cambios futuros se aplican a nuevas reservas y no alteran unilateralmente condiciones ya aceptadas. El cliente puede guardar o imprimir el documento. Las condiciones particulares deben entregarse antes del pago y conservarse junto con esta versión.',
'Un enlace en el footer facilita consulta, pero no sustituye explicar riesgos, entregar la oferta y obtener aceptación expresa en la contratación. Las comunicaciones se mantendrán claras y verificables para que ambas partes conozcan el alcance de sus obligaciones.'] ]
];
export const sources=[
['Estatuto del Consumidor — Ley 1480 de 2011','https://www1.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=44306'],
['Comercio electrónico — Ley 2439 de 2024','https://www1.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=257116'],
['Corte Constitucional — C-192 de 2026','https://www.suin-juriscol.gov.co/viewDocument.asp?id=30056645'],
['Ley General de Turismo — Ley 300 de 1996','https://www.cancilleria.gov.co/normograma/compilacion/docs/ley_0300_1996.htm'],
['Protección de datos — Ley 1581 de 2012','https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=49981'],
['Superintendencia de Industria y Comercio','https://sedeelectronica.sic.gov.co/']
];
