import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const domain = 'https://kitecartagena.com';
const phone = '573163030589';
const rnt = '292710';
const locales = {
  es: {
    prefix: '', lang: 'es-CO', locale: 'es_CO', label: 'ES',
    nav: ['Cursos','Spots','Viento','Principiantes','Viaje','Contacto'],
    slugs: ['cursos-kitesurf','spots-kitesurf-cartagena','viento-cartagena','primera-clase-kitesurf','viajar-con-equipo-kite','contacto'],
    homeTitle:'Kitesurf en Cartagena | Clases en La Boquilla',
    homeDesc:'Clases de kitesurf en Cartagena con atención personalizada, guía de viento, spots y planificación por WhatsApp.',
    eyebrow:'ESCUELA LOCAL · LA BOQUILLA · CARTAGENA',
    hero:'Aprende kitesurf donde sopla el Caribe',
    intro:'Una experiencia clara desde el primer mensaje: nivel, condiciones, seguridad, punto de encuentro y equipo se confirman antes de entrar al agua.',
    cta:'Planear mi sesión', cta2:'Ver guía de viento',
    trust:['Atención en español e inglés','Sesiones según condiciones reales','La Boquilla, Cartagena','Plan para principiantes y riders'],
    pages:[
      ['Cursos de kitesurf en Cartagena','Elige una ruta de aprendizaje, no una promesa de horas. Evaluamos tu nivel y las condiciones antes de recomendar una sesión.','Primera experiencia','Control del kite, sistemas de seguridad, zona de vuelo y decisiones básicas.','Progresión al agua','Body drag, relanzamiento y salida controlada cuando el viento y el mar lo permiten.','Rider independiente','Navegación, ceñida, transiciones y criterio para elegir equipo y spot.'],
      ['Spots de kitesurf cerca de Cartagena','No todos los spots sirven para todos los niveles. Esta guía compara acceso, orientación, espacio y logística.','La Boquilla','El punto local más práctico para clases y sesiones cerca de la ciudad. Confirma siempre la zona exacta y el estado del mar.','Las Velas y Manzanillo','Alternativas que requieren revisar acceso, obstáculos, oleaje y dirección del viento el mismo día.','Salinas del Rey','Destino reconocido fuera de Cartagena. Implica traslado y planificación propia; no lo presentamos como el mismo producto local.'],
      ['Viento en Cartagena: guía por meses','El alisio suele marcar la temporada, pero una media mensual nunca reemplaza el pronóstico ni la observación en playa.','Temporada más consistente','De diciembre a abril suelen encontrarse las ventanas más conocidas. La fuerza y el horario varían.','Meses variables','En transición y temporada lluviosa conviene mantener planes flexibles y confirmar la sesión cerca de la fecha.','Antes de salir','Consulta el pronóstico oficial, alertas marítimas y una fuente meteorológica; después valida localmente.'],
      ['Tu primera clase de kitesurf','Saber qué ocurrirá reduce nervios y mejora la seguridad. No necesitas comprar equipo antes de aprender.','Antes del agua','Objetivos, viento, límites del área, señales y liberaciones de seguridad.','Primer control','Pilotaje progresivo del kite con supervisión y distancia segura.','Progreso responsable','El paso al agua depende del control demostrado y de las condiciones, no de una foto prometida.'],
      ['Viajar a Cartagena con equipo de kite','Una guía práctica para evitar cargos sorpresa, daños y días perdidos.','Antes de volar','Revisa peso, dimensiones, reserva deportiva y reglas del trayecto completo directamente con la aerolínea.','Empaque','Protege quillas y herrajes, separa piezas, identifica la bolsa y fotografía su estado.','Al llegar','Confirma transporte, almacenamiento y condiciones antes de decidir si usar tu equipo o alquilar.'],
      ['Contacto y planificación','Cuéntanos fecha, nivel, peso aproximado, idiomas y objetivo. Te respondemos con una recomendación sujeta a viento y disponibilidad.','WhatsApp','El canal más rápido para confirmar condiciones y punto de encuentro.','Qué enviar','Fechas, experiencia previa, número de personas y si necesitas equipo.','Transparencia','No cobramos desde esta página ni prometemos viento. Primero confirmamos el plan.']
    ],
    safety:'Seguridad primero', safetyText:'La decisión final se toma con el estado real del viento, el mar, el equipo y el nivel del alumno.',
    official:'Fuentes oficiales y pronóstico', officialText:'Revisa avisos y pronósticos marítimos de DIMAR/CIOH antes de cualquier actividad. La información externa no sustituye una evaluación en playa.',
    officialLink:'Abrir CIOH–DIMAR', faq:'Preguntas frecuentes', qs:[['¿Necesito experiencia?','No. Indica que es tu primera vez para ajustar el plan.'],['¿El viento está garantizado?','No. Se confirma cerca de la sesión y puede ser necesario reprogramar.'],['¿Puedo reservar para un grupo?','Sí; comparte niveles y edades para proponer una estructura segura.']],
    footer:'Kite Cartagena · La Boquilla, Cartagena de Indias'
  },
  en: {
    prefix:'en', lang:'en', locale:'en_US', label:'EN', nav:['Lessons','Spots','Wind','Beginners','Travel','Contact'],
    slugs:['kitesurf-lessons','kitesurf-spots-cartagena','cartagena-wind-guide','first-kitesurf-lesson','travel-with-kite-gear','contact'],
    homeTitle:'Kitesurf Cartagena | Lessons in La Boquilla', homeDesc:'Kitesurf lessons in Cartagena with personal guidance, wind planning, spot information and WhatsApp support.',
    eyebrow:'LOCAL SCHOOL · LA BOQUILLA · CARTAGENA', hero:'Learn to kitesurf where the Caribbean blows', intro:'A clear experience from the first message: level, conditions, safety, meeting point and equipment are confirmed before entering the water.', cta:'Plan my session',cta2:'See the wind guide',
    trust:['Spanish & English support','Sessions based on real conditions','La Boquilla, Cartagena','Plans for beginners and riders'],
    pages:[
      ['Kitesurf lessons in Cartagena','Choose a learning path, not a promise of hours. We assess your level and conditions before recommending a session.','First experience','Kite control, safety systems, flight zone and basic decisions.','Water progression','Body drag, relaunch and controlled starts when wind and sea allow.','Independent rider','Riding, upwind skills, transitions and judgment for choosing gear and spots.'],
      ['Kitesurf spots near Cartagena','Not every spot fits every level. This guide compares access, orientation, space and logistics.','La Boquilla','The most practical local base for lessons and sessions near the city. Always confirm the exact zone and sea state.','Las Velas and Manzanillo','Alternatives that require same-day checks for access, obstacles, waves and wind direction.','Salinas del Rey','A recognized destination outside Cartagena. It requires a separate transfer and plan; we do not present it as the same local product.'],
      ['Cartagena wind guide by month','Trade winds shape the season, but monthly averages never replace a forecast or beach observation.','Most consistent season','December through April commonly offers the best-known windows. Strength and timing still vary.','Variable months','During transition and rainy periods, keep plans flexible and confirm close to the date.','Before you ride','Check official marine forecasts and warnings, then validate conditions locally.'],
      ['Your first kitesurf lesson','Knowing what happens reduces nerves and improves safety. You do not need to buy gear before learning.','Before the water','Goals, wind, area limits, signals and safety releases.','First control','Progressive kite piloting with supervision and safe distance.','Responsible progress','Moving to the water depends on demonstrated control and conditions, not a promised photo.'],
      ['Flying to Cartagena with kite gear','A practical guide to avoid surprise fees, damage and lost riding days.','Before flying','Check weight, dimensions, sports-bag booking and every flight segment directly with the airline.','Packing','Protect fins and hardware, separate parts, label the bag and photograph its condition.','On arrival','Confirm transport, storage and conditions before deciding whether to use your gear or rent.'],
      ['Contact and trip planning','Share your date, level, approximate weight, languages and goal. We reply with a plan subject to wind and availability.','WhatsApp','The fastest channel to confirm conditions and meeting point.','What to send','Dates, previous experience, number of riders and equipment needs.','Transparency','We do not charge on this page or guarantee wind. We confirm the plan first.']
    ], safety:'Safety first', safetyText:'The final decision uses the actual wind, sea, equipment and rider level.', official:'Official sources and forecast',officialText:'Check DIMAR/CIOH marine forecasts and warnings before any activity. External information does not replace a beach assessment.',officialLink:'Open CIOH–DIMAR',faq:'Frequently asked questions',qs:[['Do I need experience?','No. Tell us it is your first time so we can adapt the plan.'],['Is wind guaranteed?','No. We confirm close to the session and may need to reschedule.'],['Can I book for a group?','Yes; share levels and ages so we can suggest a safe format.']],footer:'Kite Cartagena · La Boquilla, Cartagena de Indias'
  },
  fr: {
    prefix:'fr',lang:'fr',locale:'fr_FR',label:'FR',nav:['Cours','Spots','Vent','Débutants','Voyage','Contact'],slugs:['cours-kitesurf','spots-kitesurf-cartagena','vent-cartagena','premier-cours-kitesurf','voyager-avec-materiel-kite','contact'],
    homeTitle:'Kitesurf à Cartagena | Cours à La Boquilla',homeDesc:'Cours de kitesurf à Cartagena avec accompagnement personnalisé, guide du vent et organisation par WhatsApp.',eyebrow:'ÉCOLE LOCALE · LA BOQUILLA · CARTAGENA',hero:'Apprenez le kitesurf au rythme des alizés',intro:'Une expérience claire dès le premier message : niveau, conditions, sécurité, rendez-vous et matériel sont confirmés avant la mise à l’eau.',cta:'Planifier ma session',cta2:'Voir le guide du vent',trust:['Accueil en espagnol et anglais','Sessions selon les conditions réelles','La Boquilla, Cartagena','Débutants et riders'],
    pages:[['Cours de kitesurf à Cartagena','Choisissez une progression, pas une promesse d’heures. Nous évaluons niveau et conditions avant de conseiller une session.','Première expérience','Pilotage, systèmes de sécurité, fenêtre de vol et décisions essentielles.','Progression dans l’eau','Body drag, redécollage et waterstart si le vent et la mer le permettent.','Rider autonome','Navigation, remontée au vent, transitions et choix du matériel.'],['Spots de kitesurf près de Cartagena','Chaque spot a ses contraintes. Comparez accès, orientation, espace et logistique.','La Boquilla','La base locale la plus pratique près de la ville. Confirmez toujours la zone exacte et l’état de mer.','Las Velas et Manzanillo','Des alternatives à vérifier le jour même : accès, obstacles, vagues et orientation.','Salinas del Rey','Une destination reconnue hors de Cartagena, avec transfert et organisation séparés.'],['Vent à Cartagena mois par mois','Les alizés structurent la saison, mais une moyenne ne remplace jamais la prévision ni l’observation sur plage.','Période la plus régulière','De décembre à avril se trouvent souvent les fenêtres les plus connues. Intensité et horaires varient.','Mois variables','En transition et saison des pluies, gardez un programme flexible.','Avant de naviguer','Consultez prévisions et alertes maritimes officielles, puis validez localement.'],['Votre premier cours de kitesurf','Comprendre le déroulement réduit le stress et améliore la sécurité. Aucun achat de matériel n’est nécessaire.','Avant l’eau','Objectifs, vent, limites, signaux et largages de sécurité.','Premier pilotage','Contrôle progressif de l’aile sous supervision.','Progression responsable','La mise à l’eau dépend du contrôle acquis et des conditions.'],['Voyager à Cartagena avec son matériel','Le guide pratique pour éviter frais imprévus, dégâts et journées perdues.','Avant le vol','Vérifiez poids, dimensions et réservation sportive auprès de chaque compagnie.','Emballage','Protégez ailerons et pièces, étiquetez le sac et photographiez son état.','À l’arrivée','Confirmez transport, stockage et conditions avant de choisir location ou matériel personnel.'],['Contact et organisation','Indiquez dates, niveau, poids approximatif, langues et objectif. Notre proposition dépend du vent et des disponibilités.','WhatsApp','Le moyen le plus rapide pour confirmer conditions et rendez-vous.','Informations utiles','Dates, expérience, nombre de participants et besoin de matériel.','Transparence','Aucun paiement ici et aucune garantie de vent : nous confirmons d’abord le plan.']],
    safety:'La sécurité d’abord',safetyText:'La décision finale dépend du vent, de la mer, du matériel et du niveau réel.',official:'Sources officielles et prévisions',officialText:'Consultez les bulletins maritimes et alertes DIMAR/CIOH. Une source externe ne remplace pas l’évaluation sur plage.',officialLink:'Ouvrir CIOH–DIMAR',faq:'Questions fréquentes',qs:[['Faut-il de l’expérience ?','Non. Précisez que vous débutez afin d’adapter la session.'],['Le vent est-il garanti ?','Non. La session est confirmée au plus près de la date.'],['Peut-on réserver en groupe ?','Oui ; indiquez niveaux et âges pour une formule sûre.']],footer:'Kite Cartagena · La Boquilla, Cartagena de Indias'
  },
  de: {
    prefix:'de',lang:'de',locale:'de_DE',label:'DE',nav:['Kurse','Spots','Wind','Anfänger','Reise','Kontakt'],slugs:['kitesurf-kurse','kitesurf-spots-cartagena','wind-cartagena','erste-kitesurf-stunde','reise-mit-kitegepaeck','kontakt'],
    homeTitle:'Kitesurfen in Cartagena | Kurse in La Boquilla',homeDesc:'Kitesurf-Kurse in Cartagena mit persönlicher Betreuung, Windguide und Planung per WhatsApp.',eyebrow:'LOKALE SCHULE · LA BOQUILLA · CARTAGENA',hero:'Kitesurfen lernen im karibischen Passatwind',intro:'Klarheit ab der ersten Nachricht: Level, Bedingungen, Sicherheit, Treffpunkt und Material werden vor dem Wasserstart abgestimmt.',cta:'Session planen',cta2:'Windguide ansehen',trust:['Betreuung auf Spanisch und Englisch','Sessions nach realen Bedingungen','La Boquilla, Cartagena','Für Anfänger und Rider'],
    pages:[['Kitesurf-Kurse in Cartagena','Wähle einen Lernweg statt eines Stundenversprechens. Level und Bedingungen bestimmen die passende Session.','Erste Erfahrung','Kitekontrolle, Sicherheitssysteme, Windfenster und Grundentscheidungen.','Fortschritt im Wasser','Bodydrag, Relaunch und kontrollierter Wasserstart, wenn Wind und Meer passen.','Selbständiger Rider','Fahren, Höhe laufen, Wenden und Material- sowie Spotwahl.'],['Kitesurf-Spots bei Cartagena','Nicht jeder Spot passt zu jedem Level. Vergleiche Zugang, Ausrichtung, Platz und Logistik.','La Boquilla','Die praktische lokale Basis nahe der Stadt. Genaue Zone und Seegang immer aktuell prüfen.','Las Velas und Manzanillo','Alternativen, die am selben Tag auf Zugang, Hindernisse, Wellen und Windrichtung geprüft werden müssen.','Salinas del Rey','Bekanntes Ziel außerhalb Cartagenas mit eigenem Transfer und separater Planung.'],['Wind in Cartagena nach Monaten','Der Passat prägt die Saison, doch Monatsmittel ersetzen nie Vorhersage und Beobachtung am Strand.','Beständigste Zeit','Dezember bis April bietet häufig die bekanntesten Windfenster. Stärke und Uhrzeit variieren.','Wechselhafte Monate','In Übergangs- und Regenzeit flexibel bleiben und kurzfristig bestätigen.','Vor der Session','Offizielle Seewetterberichte und Warnungen prüfen und vor Ort bestätigen.'],['Deine erste Kitesurf-Stunde','Zu wissen, was passiert, senkt Nervosität und verbessert die Sicherheit. Du musst vorher keine Ausrüstung kaufen.','Vor dem Wasser','Ziele, Wind, Bereichsgrenzen, Signale und Sicherheitssysteme.','Erste Kontrolle','Schrittweise Kite-Steuerung unter Aufsicht und mit Sicherheitsabstand.','Verantwortlicher Fortschritt','Der Gang ins Wasser hängt von Kontrolle und Bedingungen ab.'],['Mit Kitegepäck nach Cartagena','Praktische Tipps gegen Überraschungsgebühren, Schäden und verlorene Wassertage.','Vor dem Flug','Gewicht, Maße, Sportgepäck und jedes Flugsegment direkt bei der Airline prüfen.','Packen','Finnen und Teile schützen, Tasche markieren und Zustand fotografieren.','Bei Ankunft','Transport, Lagerung und Bedingungen klären, bevor du Miete oder eigenes Material wählst.'],['Kontakt und Reiseplanung','Sende Datum, Level, ungefähres Gewicht, Sprachen und Ziel. Unser Vorschlag bleibt wind- und verfügbarkeitsabhängig.','WhatsApp','Der schnellste Weg, Bedingungen und Treffpunkt abzustimmen.','Wichtige Angaben','Datum, Erfahrung, Personenzahl und Materialbedarf.','Transparenz','Keine Zahlung auf dieser Seite und keine Windgarantie. Erst wird der Plan bestätigt.']],
    safety:'Sicherheit zuerst',safetyText:'Die Entscheidung richtet sich nach aktuellem Wind, Meer, Material und tatsächlichem Fahrkönnen.',official:'Offizielle Quellen und Vorhersage',officialText:'Vor jeder Aktivität DIMAR/CIOH-Seewetter und Warnungen prüfen. Externe Daten ersetzen keine Beurteilung am Strand.',officialLink:'CIOH–DIMAR öffnen',faq:'Häufige Fragen',qs:[['Brauche ich Erfahrung?','Nein. Teile mit, dass es dein erstes Mal ist.'],['Ist Wind garantiert?','Nein. Wir bestätigen kurzfristig und verschieben bei Bedarf.'],['Sind Gruppen möglich?','Ja; nenne Level und Alter für ein sicheres Format.']],footer:'Kite Cartagena · La Boquilla, Cartagena de Indias'
  }
};

const esc = s => String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const rich = {
  es: {
    labels:{guide:'Guía práctica',plan:'Cómo planearlo',expect:'Qué esperar',faq:'Preguntas sobre esta guía',related:'Sigue preparando tu viaje'},
    intro:[
      'Cartagena combina clima tropical, acceso urbano y una costa expuesta a los alisios. Aun así, una buena sesión no se decide por el calendario solamente: nivel, peso, tamaño de kite, dirección, rachas, oleaje y espacio disponible deben revisarse juntos.',
      'Si viajas desde Estados Unidos o Europa, envía fechas y nivel antes de reservar alojamiento alrededor de una sesión concreta. Te ayudamos a construir un plan flexible y a confirmar el punto de encuentro por WhatsApp cerca del día.',
      'La información de esta guía sirve para preparar preguntas y reducir imprevistos. No es una predicción en vivo ni reemplaza la decisión del instructor o las alertas de la autoridad marítima.'
    ],
    plans:[
      ['Antes de reservar','Comparte fechas, experiencia, peso aproximado, número de personas e idioma. Así se puede estimar equipo, duración y formato sin venderte una opción genérica.'],
      ['Antes de salir','Consulta el boletín de CIOH–DIMAR, confirma la sesión y lleva protección solar resistente al agua, hidratación y ropa que permita moverte.'],
      ['En la playa','Revisa el área de lanzamiento, obstáculos, bañistas y plan de emergencia. Si las condiciones no corresponden a tu nivel, se cambia el ejercicio o se reprograma.'],
      ['Después','Registra lo aprendido y el objetivo siguiente. La continuidad vale más que intentar saltar etapas en una sola sesión.']
    ],
    qs:[['¿Puedo organizarlo desde Estados Unidos o Europa?','Sí. Coordinamos por WhatsApp antes del viaje; la confirmación final depende de condiciones y disponibilidad.'],['¿Dónde se realiza?','La base de referencia es La Boquilla, Cartagena. La zona exacta se confirma el mismo día según condiciones y operación local.'],['¿Puedo pagar desde la web?','Todavía no. Primero confirmamos por escrito disponibilidad, alcance, precio final y política aplicable.'],['¿Quién comercializa la experiencia?','Kite Cartagena funciona como marca de la experiencia comercializada por Dunas & Olas, prestador turístico con RNT 292710.']],
    travelTitle:'Planificación para visitantes internacionales',travelText:'Desde el aeropuerto Rafael Núñez, La Boquilla queda al norte del centro histórico. El tiempo real depende del tráfico y del alojamiento. No fijes una conexión o vuelo inmediatamente después de la sesión: deja margen para traslados, cambios de viento y limpieza del equipo.',
    legal:'Experiencia comercializada por Dunas & Olas · RNT 292710'
  },
  en: {
    labels:{guide:'Practical guide',plan:'How to plan it',expect:'What to expect',faq:'Questions about this guide',related:'Keep planning your trip'},
    intro:['Cartagena combines tropical weather, urban access and a coast exposed to the trade winds. A good session is never chosen by the calendar alone: level, weight, kite size, direction, gusts, waves and available space must be assessed together.','If you are travelling from the United States, Canada or Europe, send your dates and riding level before building a day around one fixed session. We help you keep the plan flexible and confirm the meeting point by WhatsApp close to the date.','Use this guide to ask better questions and avoid surprises. It is not a live forecast and it never overrides an instructor’s decision or official marine warnings.'],
    plans:[['Before booking','Share dates, experience, approximate weight, party size and preferred language. This lets us suggest equipment and format instead of selling a generic package.'],['Before leaving','Check the CIOH–DIMAR bulletin, reconfirm your session and bring water-resistant sun protection, hydration and comfortable active clothing.'],['At the beach','Review the launch area, obstacles, swimmers and emergency plan. If conditions do not fit your level, the exercise changes or the session is rescheduled.'],['Afterwards','Record what you learned and the next objective. Consistent progression is more useful than skipping stages in one session.']],
    qs:[['Can I arrange everything from the US or Europe?','Yes. We coordinate by WhatsApp before your trip; final confirmation remains subject to conditions and availability.'],['Where do sessions take place?','Our reference base is La Boquilla, Cartagena. The exact area is confirmed on the day according to conditions and local operations.'],['Can I pay on this website?','Not yet. We first confirm availability, scope, final price and the applicable policy in writing.'],['Who sells the experience?','Kite Cartagena is the experience brand marketed by Dunas & Olas, a registered tourism provider under RNT 292710.']],
    travelTitle:'Planning for international visitors',travelText:'La Boquilla is north of Cartagena’s historic centre and Rafael Núñez airport. Actual transfer time depends on traffic and accommodation. Avoid scheduling a tight flight or connection immediately after a session; allow time for transfers, wind changes and rinsing equipment.',
    legal:'Experience marketed by Dunas & Olas · RNT 292710'
  },
  fr: {
    labels:{guide:'Guide pratique',plan:'Comment organiser la session',expect:'À quoi s’attendre',faq:'Questions sur ce guide',related:'Continuez à préparer votre voyage'},
    intro:['Cartagena réunit climat tropical, accès urbain et côte exposée aux alizés. Une bonne session ne se choisit jamais selon le calendrier uniquement : niveau, poids, taille de l’aile, direction, rafales, vagues et espace doivent être évalués ensemble.','Si vous venez de France, Belgique, Suisse ou d’un autre pays européen, envoyez vos dates et votre niveau avant d’organiser une journée autour d’un horaire fixe. Nous gardons le programme flexible et confirmons le rendez-vous par WhatsApp.','Ce guide aide à poser les bonnes questions et à éviter les surprises. Il ne s’agit pas d’une prévision en direct et il ne remplace ni la décision du moniteur ni les alertes maritimes officielles.'],
    plans:[['Avant de réserver','Indiquez dates, expérience, poids approximatif, nombre de participants et langue. Nous pouvons ainsi proposer matériel et format sans forfait générique.'],['Avant de partir','Consultez le bulletin CIOH–DIMAR, reconfirmez la session et prévoyez protection solaire résistante à l’eau, hydratation et tenue confortable.'],['Sur la plage','Vérifiez zone de décollage, obstacles, baigneurs et plan d’urgence. Si les conditions ne conviennent pas au niveau, l’exercice change ou la session est reportée.'],['Après','Notez les acquis et le prochain objectif. Une progression régulière est préférable à des étapes brûlées en une seule session.']],
    qs:[['Puis-je tout organiser depuis l’Europe ?','Oui. Nous coordonnons par WhatsApp avant le voyage ; la confirmation finale dépend des conditions et disponibilités.'],['Où ont lieu les sessions ?','Notre base de référence est La Boquilla, Cartagena. La zone exacte est confirmée le jour même.'],['Puis-je payer sur le site ?','Pas encore. Disponibilité, prestation, prix final et conditions sont d’abord confirmés par écrit.'],['Qui commercialise l’expérience ?','Kite Cartagena est la marque de l’expérience commercialisée par Dunas & Olas, prestataire touristique enregistré sous le RNT 292710.']],
    travelTitle:'Organisation pour les visiteurs internationaux',travelText:'La Boquilla se trouve au nord du centre historique et de l’aéroport Rafael Núñez. Le trajet dépend du trafic et de votre hébergement. Évitez un vol ou une correspondance juste après la session ; gardez une marge pour le transport, le vent et le rinçage du matériel.',
    legal:'Expérience commercialisée par Dunas & Olas · RNT 292710'
  },
  de: {
    labels:{guide:'Praktischer Guide',plan:'So planst du',expect:'Was dich erwartet',faq:'Fragen zu diesem Guide',related:'Reise weiter planen'},
    intro:['Cartagena verbindet tropisches Klima, kurze Wege und eine den Passatwinden ausgesetzte Küste. Eine gute Session wird nie nur nach Kalender gewählt: Level, Gewicht, Kitegröße, Richtung, Böen, Wellen und verfügbarer Platz müssen zusammen bewertet werden.','Wenn du aus Deutschland, Österreich, der Schweiz oder einem anderen europäischen Land anreist, sende vorab Reisedaten und Fahrlevel. Wir halten den Plan flexibel und bestätigen den Treffpunkt kurzfristig per WhatsApp.','Dieser Guide hilft, die richtigen Fragen zu stellen und Überraschungen zu vermeiden. Er ist keine Live-Vorhersage und ersetzt weder die Entscheidung des Trainers noch offizielle Seewetterwarnungen.'],
    plans:[['Vor der Buchung','Sende Reisedaten, Erfahrung, ungefähres Gewicht, Gruppengröße und Sprache. So können Material und Format passend statt pauschal vorgeschlagen werden.'],['Vor der Abfahrt','CIOH–DIMAR-Bericht prüfen, Session bestätigen sowie wasserfesten Sonnenschutz, Trinkwasser und bewegungsfreundliche Kleidung mitnehmen.'],['Am Strand','Startzone, Hindernisse, Badegäste und Notfallplan prüfen. Passen die Bedingungen nicht zum Level, wird die Übung geändert oder verschoben.'],['Danach','Lernfortschritt und nächstes Ziel notieren. Kontinuierlicher Aufbau ist wertvoller als übersprungene Schritte in einer Session.']],
    qs:[['Kann ich alles aus Europa organisieren?','Ja. Wir koordinieren vor der Reise per WhatsApp; die endgültige Bestätigung hängt von Bedingungen und Verfügbarkeit ab.'],['Wo finden die Sessions statt?','Unser Referenzstandort ist La Boquilla, Cartagena. Der genaue Bereich wird am selben Tag bestätigt.'],['Kann ich auf der Website bezahlen?','Noch nicht. Verfügbarkeit, Umfang, Endpreis und Bedingungen werden zuerst schriftlich bestätigt.'],['Wer vermarktet das Erlebnis?','Kite Cartagena ist die Erlebnismarke, die von Dunas & Olas vermarktet wird, einem unter RNT 292710 registrierten Tourismusanbieter.']],
    travelTitle:'Planung für internationale Gäste',travelText:'La Boquilla liegt nördlich der Altstadt und des Flughafens Rafael Núñez. Die tatsächliche Fahrzeit hängt von Verkehr und Unterkunft ab. Plane keinen knappen Flug direkt nach der Session; lasse Zeit für Transfer, Windänderungen und Materialpflege.',
    legal:'Erlebnis vermarktet durch Dunas & Olas · RNT 292710'
  }
};
const href = (l, slug='') => `${l.prefix ? '/'+l.prefix : ''}/${slug ? slug+'/' : ''}`;
const alternates = slugIndex => Object.values(locales).map(l=>`<link rel="alternate" hreflang="${l.lang}" href="${domain}${href(l,slugIndex == null ? '' : l.slugs[slugIndex])}">`).join('\n') + `\n<link rel="alternate" hreflang="x-default" href="${domain}${href(locales.es,slugIndex == null ? '' : locales.es.slugs[slugIndex])}">`;
const langMenu = slugIndex => Object.values(locales).map(l=>`<a href="${href(l,slugIndex == null ? '' : l.slugs[slugIndex])}" lang="${l.lang}">${l.label}</a>`).join('');

function shell(l,{title,desc,slugIndex=null,body,faq=[]}) {
 const url = domain + href(l, slugIndex == null ? '' : l.slugs[slugIndex]);
 const nav = l.nav.map((x,i)=>`<a href="${href(l,l.slugs[i])}">${x}</a>`).join('');
 const graph=[{'@type':['LocalBusiness','SportsActivityLocation'],'@id':`${domain}/#business`,name:'Kite Cartagena',url:domain,telephone:'+573163030589',image:`${domain}/images/kite-cartagena-cover.png`,areaServed:['Cartagena de Indias','United States','Europe'],address:{'@type':'PostalAddress',addressLocality:'Cartagena de Indias',addressRegion:'Bolívar',addressCountry:'CO'},parentOrganization:{'@type':'TravelAgency',name:'Dunas & Olas',identifier:{'@type':'PropertyValue',name:'Registro Nacional de Turismo',value:rnt}},sameAs:['https://www.instagram.com/kitecartagena/','https://www.facebook.com/profile.php?id=61568646471234']},{'@type':'WebPage','@id':url,url,name:title,description:desc,inLanguage:l.lang,isPartOf:{'@id':`${domain}/#website`}}];
 if(faq.length) graph.push({'@type':'FAQPage',mainEntity:faq.map(([name,text])=>({'@type':'Question',name,acceptedAnswer:{'@type':'Answer',text}}))});
 return `<!doctype html><html lang="${l.lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><meta name="robots" content="index,follow,max-image-preview:large"><meta name="geo.region" content="CO-BOL"><meta name="geo.placename" content="Cartagena de Indias"><link rel="canonical" href="${url}">${alternates(slugIndex)}<meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${url}"><meta property="og:image" content="${domain}/images/social/01-kitesurf-cartagena-action.webp"><meta property="og:locale" content="${l.locale}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(desc)}"><meta name="twitter:image" content="${domain}/images/social/01-kitesurf-cartagena-action.webp"><link rel="icon" href="/favicon.svg"><link rel="manifest" href="/site.webmanifest"><link rel="stylesheet" href="/assets/multilingual.css"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':graph})}</script></head><body><a class="skip" href="#main-content">Skip</a><header><a class="brand" href="${href(l)}"><img src="/images/kite-cartagena-profile.png" alt="" width="54" height="54"><span>KITE<br>CARTAGENA</span></a><nav>${nav}</nav><div class="langs">${langMenu(slugIndex)}</div></header><main id="main-content">${body}</main><footer><strong>${l.footer}</strong><span>${rich[l.prefix||'es'].legal}</span><a href="https://wa.me/${phone}?text=${encodeURIComponent('Hola Kite Cartagena, quiero información')}" rel="noopener">WhatsApp +57 316 303 0589</a><a href="https://www.cioh.org.co/meteorologia/" target="_blank" rel="noopener">CIOH · DIMAR</a></footer></body></html>`;
}

function home(l){
 const cards=l.pages.slice(0,5).map((p,i)=>`<a class="card" href="${href(l,l.slugs[i])}"><span>0${i+1}</span><h2>${p[0]}</h2><p>${p[1]}</p></a>`).join('');
 const faq=l.qs.map(q=>`<details><summary>${q[0]}</summary><p>${q[1]}</p></details>`).join('');
 return shell(l,{title:l.homeTitle,desc:l.homeDesc,body:`<section class="hero"><div><p class="eyebrow">${l.eyebrow}</p><h1>${l.hero}</h1><p class="lead">${l.intro}</p><div class="actions"><a class="primary" href="https://wa.me/${phone}">${l.cta}</a><a class="secondary" href="${href(l,l.slugs[2])}">${l.cta2}</a></div></div></section><section class="trust">${l.trust.map(x=>`<span>✓ ${x}</span>`).join('')}</section><section class="grid">${cards}</section><section class="split"><div><p class="eyebrow">${l.safety}</p><h2>${l.safety}</h2><p>${l.safetyText}</p></div><div><p class="eyebrow">DIMAR · CIOH</p><h2>${l.official}</h2><p>${l.officialText}</p><a class="textlink" href="https://www.cioh.org.co/meteorologia/" target="_blank" rel="noopener">${l.officialLink} →</a></div></section><section class="faq"><h2>${l.faq}</h2>${faq}</section>`});
}

function page(l,i){const key=l.prefix||'es',x=rich[key],p=l.pages[i]; const sections=[[p[2],p[3]],[p[4],p[5]],[p[6],p[7]]].map(([h,t],n)=>`<article><span>0${n+1}</span><h2>${h}</h2><p>${t}</p></article>`).join(''); const wind=i===2?`<section class="wind"><h2>Wind planning / Planificación</h2><div class="bars" role="img" aria-label="Seasonal orientation chart">${[72,78,84,70,48,36,30,28,34,42,55,68].map((v,n)=>`<i style="--v:${v}%"><b>${['J','F','M','A','M','J','J','A','S','O','N','D'][n]}</b></i>`).join('')}</div><small>Orientation chart — not a live forecast. Always verify DIMAR/CIOH and local conditions.</small></section>`:''; const guide=`<section class="content"><p class="eyebrow">${x.labels.guide}</p>${x.intro.map(t=>`<p>${t}</p>`).join('')}<h2>${x.labels.plan}</h2><div class="articles">${x.plans.map(([h,t],n)=>`<article><span>0${n+4}</span><h3>${h}</h3><p>${t}</p></article>`).join('')}</div><h2>${x.travelTitle}</h2><p>${x.travelText}</p></section>`; const faq=`<section class="faq"><h2>${x.labels.faq}</h2>${x.qs.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</section>`;return shell(l,{title:`${p[0]} | Kite Cartagena`,desc:p[1],slugIndex:i,faq:x.qs,body:`<section class="pagehero"><p class="eyebrow">KITE CARTAGENA · GUIDE</p><h1>${p[0]}</h1><p class="lead">${p[1]}</p><a class="primary" href="https://wa.me/${phone}?text=${encodeURIComponent('Hello Kite Cartagena, I would like to plan a session')}">${l.cta}</a></section><section class="articles">${sections}</section>${guide}${wind}<section class="official"><h2>${l.official}</h2><p>${l.officialText}</p><a class="secondary" href="https://www.cioh.org.co/meteorologia/" target="_blank" rel="noopener">${l.officialLink}</a></section>${faq}`});}

for(const l of Object.values(locales)){
 const base=path.join(root,l.prefix); fs.mkdirSync(base,{recursive:true}); fs.writeFileSync(path.join(base,'index.html'),home(l));
 l.slugs.forEach((slug,i)=>{const dir=path.join(base,slug);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),page(l,i));});
}
const urls=[];for(const l of Object.values(locales)){urls.push(domain+href(l));l.slugs.forEach(s=>urls.push(domain+href(l,s)));}
for (const legacy of ['about.html','experiences.html','terms.html','blog/','blog/best-time-kitesurf-cartagena/','blog/first-kitesurf-jump-guide/','blog/how-long-to-learn-kitesurfing/','blog/kite-wing-foil-differences/','blog/kitesurf-la-boquilla-spot-guide/','blog/kitesurf-packing-list/','blog/kitesurfing-for-beginners-cartagena/','blog/safety-tips-cartagena/','blog/top-water-sports-cartagena/']) urls.push(domain+'/'+legacy);
fs.writeFileSync(path.join(root,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n${urls.map(u=>`  <url><loc>${u}</loc><lastmod>2026-09-14</lastmod></url>`).join('\n')}\n</urlset>\n`);
console.log(`Generated ${urls.length} localized pages.`);
